var data = {
    current_page: 1,
    data: [
        {
            id: 310552,
            company: 'Surya',
            account: 99028153,
            status: 'Pantau',
            status_stp: 'A-Book',
        },
        {
            id: 310553,
            company: 'Surya',
            account: 91730267,
            status: 'Aman',
            status_stp: 'A-Book',
        },
        {
            id: 310554,
            company: 'Valutrades',
            account: 81256490,
            status: 'Aman',
            status_stp: 'B-Book',
        },
        {
            id: 310555,
            company: 'Valutrades',
            account: 78923401,
            status: 'Pantau',
            status_stp: 'A-Book VT',
        },
        {
            id: 310556,
            company: 'Surya',
            account: 92367325,
            status: 'Aman',
            status_stp: 'A-Book',
        },
        {
            id: 310557,
            company: 'Valutrades',
            account: 82618954,
            status: 'Aman',
            status_stp: 'B-Book',
        },
        {
            id: 310558,
            company: 'Surya',
            account: 91002356,
            status: 'Aman',
            status_stp: 'A-Book',
        },
        {
            id: 310559,
            company: 'Surya',
            account: 90126742,
            status: 'Aman',
            status_stp: 'A-Book',
        },
        {
            id: 310560,
            company: 'Surya',
            account: 92067123,
            status: 'Aman',
            status_stp: 'B-Book',
        },
        {
            id: 310561,
            company: 'Valutrades',
            account: 72190262,
            status: 'Aman',
            status_stp: 'A-Book VT 50%',
        },
    ],
    first_page_url: 'https://rpt-rm-dev.surya-am.com/api/v1/biglot?per_page=15&page=1',
    from: 1,
    last_page: 1,
    last_page_url: 'https://rpt-rm-dev.surya-am.com/api/v1/biglot?per_page=15&page=5397',
    links: [
        {
            url: null,
            label: '&laquo; Previous',
            active: false,
        },
        {
            url: 'https://rpt-rm-dev.surya-am.com/api/v1/biglot?per_page=15&page=1',
            label: '1',
            active: true,
        },
        {
            url: 'https://rpt-rm-dev.surya-am.com/api/v1/biglot?per_page=15&page=2',
            label: '2',
            active: false,
        },
        {
            url: 'https://rpt-rm-dev.surya-am.com/api/v1/biglot?per_page=15&page=3',
            label: '3',
            active: false,
        },
        {
            url: 'https://rpt-rm-dev.surya-am.com/api/v1/biglot?per_page=15&page=4',
            label: '4',
            active: false,
        },
        {
            url: 'https://rpt-rm-dev.surya-am.com/api/v1/biglot?per_page=15&page=5',
            label: '5',
            active: false,
        },
        {
            url: 'https://rpt-rm-dev.surya-am.com/api/v1/biglot?per_page=15&page=6',
            label: '6',
            active: false,
        },
        {
            url: 'https://rpt-rm-dev.surya-am.com/api/v1/biglot?per_page=15&page=7',
            label: '7',
            active: false,
        },
        {
            url: 'https://rpt-rm-dev.surya-am.com/api/v1/biglot?per_page=15&page=8',
            label: '8',
            active: false,
        },
        {
            url: 'https://rpt-rm-dev.surya-am.com/api/v1/biglot?per_page=15&page=9',
            label: '9',
            active: false,
        },
        {
            url: 'https://rpt-rm-dev.surya-am.com/api/v1/biglot?per_page=15&page=10',
            label: '10',
            active: false,
        },
        {
            url: null,
            label: '...',
            active: false,
        },
        {
            url: 'https://rpt-rm-dev.surya-am.com/api/v1/biglot?per_page=15&page=5396',
            label: '5396',
            active: false,
        },
        {
            url: 'https://rpt-rm-dev.surya-am.com/api/v1/biglot?per_page=15&page=5397',
            label: '5397',
            active: false,
        },
        {
            url: 'https://rpt-rm-dev.surya-am.com/api/v1/biglot?per_page=15&page=2',
            label: 'Next &raquo;',
            active: false,
        },
    ],
    next_page_url: 'https://rpt-rm-dev.surya-am.com/api/v1/biglot?per_page=15&page=2',
    path: 'https://rpt-rm-dev.surya-am.com/api/v1/biglot',
    per_page: 10,
    prev_page_url: null,
    to: 10,
    total: 10,
};

module.exports = data;
