var autoConfig = {
    status: "success",
    message: "Successfully",
    data: {
        current_page: 1,
        data: [
            {
                id: 1,
                login: "ALL",
                server: "ALL",
                symbol: "ALL",
                min_lot: "5.00",
                stop1: 3,
                stop2: 0,
                volume_percent1: 40,
                volume_percent2: 0,
                trading_account: 2005965575,
                trading_account_server: "MT4IN4",
                status: 1,
                auto_update: 0,
                created_at: null,
                updated_at: null,
            },
            {
                id: 2,
                login: "ALL",
                server: "MT4IN1",
                symbol: "AUDCADb,AUDCADn,AUDCADs,AUDCADv",
                min_lot: "5.00",
                stop1: 1.5,
                stop2: 0,
                volume_percent1: 40,
                volume_percent2: 0,
                trading_account: 2005965575,
                trading_account_server: "MT4IN4",
                status: 1,
                auto_update: 1,
                created_at: null,
                updated_at: null,
            },
            {
                id: 3,
                login: "ALL",
                server: "MT4IN2",
                symbol: "AUDCADv,AUDCADn",
                min_lot: "5.00",
                stop1: 1.5,
                stop2: 0,
                volume_percent1: 45,
                volume_percent2: 0,
                trading_account: 2005965575,
                trading_account_server: "MT4IN4",
                status: 1,
                auto_update: 1,
                created_at: null,
                updated_at: "2023-04-03 11:25:41",
            },
            {
                id: 4,
                login: "ALL",
                server: "MT4IN3",
                symbol: "AUDCADb,AUDCADn,AUDCADs,AUDCADv",
                min_lot: "5.00",
                stop1: 1.5,
                stop2: 0,
                volume_percent1: 40,
                volume_percent2: 0,
                trading_account: 2005965575,
                trading_account_server: "MT4IN4",
                status: 1,
                auto_update: 1,
                created_at: null,
                updated_at: null,
            },
            {
                id: 6,
                login: "ALL",
                server: "MT4IN2",
                symbol: "AUDCHFb,AUDCHFn,AUDCHFs,AUDCHFv",
                min_lot: "5.00",
                stop1: 1.5,
                stop2: 0,
                volume_percent1: 40,
                volume_percent2: 0,
                trading_account: 2005965575,
                trading_account_server: "MT4IN4",
                status: 1,
                auto_update: 1,
                created_at: null,
                updated_at: "2023-04-03 11:15:30",
            },
            {
                id: 7,
                login: "ALL",
                server: "MT4IN3",
                symbol: "AUDCADb,AUDCADn,USDJPY",
                min_lot: "5.00",
                stop1: 1.5,
                stop2: 0,
                volume_percent1: 42,
                volume_percent2: 0,
                trading_account: 2005965575,
                trading_account_server: "MT4IN4",
                status: 1,
                auto_update: 1,
                created_at: null,
                updated_at: "2023-04-03 11:24:34",
            },
            {
                id: 8,
                login: "ALL",
                server: "MT4IN1",
                symbol: "AUDJPY,AUDJPY.,AUDJPY.i,AUDJPY.m,AUDJPYb,AUDJPYn,AUDJPYs,AUDJPYv",
                min_lot: "5.00",
                stop1: 1.5,
                stop2: 0,
                volume_percent1: 40,
                volume_percent2: 0,
                trading_account: 2005965575,
                trading_account_server: "MT4IN4",
                status: 1,
                auto_update: 1,
                created_at: null,
                updated_at: null,
            },
            {
                id: 9,
                login: "ALL",
                server: "MT4IN2",
                symbol: "AUDJPY,AUDJPY.,AUDJPY.i,AUDJPY.m,AUDJPYb,AUDJPYn,AUDJPYs,AUDJPYv",
                min_lot: "5.00",
                stop1: 1.5,
                stop2: 0,
                volume_percent1: 40,
                volume_percent2: 0,
                trading_account: 2005965575,
                trading_account_server: "MT4IN4",
                status: 1,
                auto_update: 1,
                created_at: null,
                updated_at: null,
            },
            {
                id: 10,
                login: "ALL",
                server: "MT4IN3",
                symbol: "AUDJPY,AUDJPY.,AUDJPY.i,AUDJPY.m,AUDJPYb,AUDJPYn,AUDJPYs,AUDJPYv",
                min_lot: "5.00",
                stop1: 1.5,
                stop2: 0,
                volume_percent1: 40,
                volume_percent2: 0,
                trading_account: 2005965575,
                trading_account_server: "MT4IN4",
                status: 1,
                auto_update: 1,
                created_at: null,
                updated_at: null,
            },
            {
                id: 11,
                login: "ALL",
                server: "MT4IN1",
                symbol: "AUDNZD,AUDNZD.,AUDNZD.i,AUDNZD.m,AUDNZDb,AUDNZDn,AUDNZDs,AUDNZDv",
                min_lot: "5.00",
                stop1: 1,
                stop2: 0,
                volume_percent1: 40,
                volume_percent2: 0,
                trading_account: 2005965575,
                trading_account_server: "MT4IN4",
                status: 1,
                auto_update: 1,
                created_at: null,
                updated_at: null,
            },
        ],
        first_page_url:
            "https://trailing-rmv3-dev.surya-am.com/api/v1/autoconfig?per_page=10&page=1",
        from: 1,
        last_page: 236,
        last_page_url:
            "https://trailing-rmv3-dev.surya-am.com/api/v1/autoconfig?per_page=10&page=236",
        links: [
            { url: null, label: "&laquo; Previous", active: false },
            {
                url: "https://trailing-rmv3-dev.surya-am.com/api/v1/autoconfig?per_page=10&page=1",
                label: "1",
                active: true,
            },
            {
                url: "https://trailing-rmv3-dev.surya-am.com/api/v1/autoconfig?per_page=10&page=2",
                label: "2",
                active: false,
            },
            {
                url: "https://trailing-rmv3-dev.surya-am.com/api/v1/autoconfig?per_page=10&page=3",
                label: "3",
                active: false,
            },
            {
                url: "https://trailing-rmv3-dev.surya-am.com/api/v1/autoconfig?per_page=10&page=4",
                label: "4",
                active: false,
            },
            {
                url: "https://trailing-rmv3-dev.surya-am.com/api/v1/autoconfig?per_page=10&page=5",
                label: "5",
                active: false,
            },
            {
                url: "https://trailing-rmv3-dev.surya-am.com/api/v1/autoconfig?per_page=10&page=6",
                label: "6",
                active: false,
            },
            {
                url: "https://trailing-rmv3-dev.surya-am.com/api/v1/autoconfig?per_page=10&page=7",
                label: "7",
                active: false,
            },
            {
                url: "https://trailing-rmv3-dev.surya-am.com/api/v1/autoconfig?per_page=10&page=8",
                label: "8",
                active: false,
            },
            {
                url: "https://trailing-rmv3-dev.surya-am.com/api/v1/autoconfig?per_page=10&page=9",
                label: "9",
                active: false,
            },
            {
                url: "https://trailing-rmv3-dev.surya-am.com/api/v1/autoconfig?per_page=10&page=10",
                label: "10",
                active: false,
            },
            { url: null, label: "...", active: false },
            {
                url: "https://trailing-rmv3-dev.surya-am.com/api/v1/autoconfig?per_page=10&page=235",
                label: "235",
                active: false,
            },
            {
                url: "https://trailing-rmv3-dev.surya-am.com/api/v1/autoconfig?per_page=10&page=236",
                label: "236",
                active: false,
            },
            {
                url: "https://trailing-rmv3-dev.surya-am.com/api/v1/autoconfig?per_page=10&page=2",
                label: "Next &raquo;",
                active: false,
            },
        ],
        next_page_url:
            "https://trailing-rmv3-dev.surya-am.com/api/v1/autoconfig?per_page=10&page=2",
        path: "https://trailing-rmv3-dev.surya-am.com/api/v1/autoconfig",
        per_page: 10,
        prev_page_url: null,
        to: 10,
        total: 2356,
    },
};

module.exports = { autoConfig };
