var data = {
    current_page: 1,
    data: [
        {
            code: 'M',
            person_id: 2927,
            person: 'M-2927',
            company: 'Surya',
            name: 'load test 4',
            status: 'Baru',
            status_stp: null,
            high_leverage_percent: '0.00',
            slippage_percent: '0.00',
            scalper_percent: '0.00',
            av_percent: '0.00',
            nnhl_percent: null,
            pl_2_5_percent: '0.06',
            equity: 0,
            pl_a_book: 0,
            pl_lifetime: -6721.68,
            pl_today: 0,
            pl_yesterday: 0.31,
            pl_weekly: 0,
            pl_monthly: 0,
            last_equity: 60544.77,
            margin: 0,
            margin_level: 0,
            total_ticket: '17',
            high_leverage_score: '0',
            daily_pl_20_score: '0',
            av_profit_score: '0',
            pl_2_5_score: '1',
            opc_20_score: '0',
            opp_50_score: '0',
            big_lot_score: '0',
            scalper_score: '0',
            slippage_score: '0',
            nnhl_score: '0',
            high_leverage: '0 % (0/17)',
            av_profit: '0 % (0/17)',
            pl_2_5: '5.88 % (1/17)',
            scalper: '0 % (0/34)',
            slippage: '0 % (0/34)',
            nnhl: '0 % (0/0)',
        },
        {
            code: 'M',
            person_id: 54077,
            person: 'M-54077',
            company: 'Surya',
            name: 'RICHARD MARK',
            status: 'Pantau',
            status_stp: null,
            high_leverage_percent: '0.29',
            slippage_percent: '0.00',
            scalper_percent: '0.15',
            av_percent: '0.02',
            nnhl_percent: null,
            pl_2_5_percent: '0.00',
            equity: 0,
            pl_a_book: 0,
            pl_lifetime: -240.16,
            pl_today: 0,
            pl_yesterday: 0,
            pl_weekly: 0,
            pl_monthly: 0,
            last_equity: 0,
            margin: 0,
            margin_level: 0,
            total_ticket: '731',
            high_leverage_score: '211',
            daily_pl_20_score: '7',
            av_profit_score: '11',
            pl_2_5_score: '1',
            opc_20_score: '0',
            opp_50_score: '0',
            big_lot_score: '0',
            scalper_score: '213',
            slippage_score: '6',
            nnhl_score: '0',
            high_leverage: '28.86 % (211/731)',
            av_profit: '1.5 % (11/731)',
            pl_2_5: '0.14 % (1/731)',
            scalper: '14.57 % (213/1462)',
            slippage: '0.41 % (6/1462)',
            nnhl: '0 % (0/0)',
        },
        {
            code: 'M',
            person_id: 77028,
            person: 'M-77028',
            company: 'Surya',
            name: 'Muhammad Fadhillah Putra ST',
            status: 'Baru',
            status_stp: null,
            high_leverage_percent: '0.32',
            slippage_percent: '0.00',
            scalper_percent: '0.27',
            av_percent: '0.00',
            nnhl_percent: null,
            pl_2_5_percent: '0.00',
            equity: 0,
            pl_a_book: 0,
            pl_lifetime: -413.73,
            pl_today: 0,
            pl_yesterday: 0,
            pl_weekly: 0,
            pl_monthly: 0,
            last_equity: 0,
            margin: 0,
            margin_level: 0,
            total_ticket: '232',
            high_leverage_score: '75',
            daily_pl_20_score: '0',
            av_profit_score: '1',
            pl_2_5_score: '1',
            opc_20_score: '0',
            opp_50_score: '0',
            big_lot_score: '0',
            scalper_score: '126',
            slippage_score: '0',
            nnhl_score: '0',
            high_leverage: '32.33 % (75/232)',
            av_profit: '0.43 % (1/232)',
            pl_2_5: '0.43 % (1/232)',
            scalper: '27.16 % (126/464)',
            slippage: '0 % (0/464)',
            nnhl: '0 % (0/0)',
        },
        {
            code: 'M',
            person_id: 83194,
            person: 'M-83194',
            company: 'Surya',
            name: 'Mike Lim',
            status: 'Baru',
            status_stp: null,
            high_leverage_percent: '0.11',
            slippage_percent: '0.00',
            scalper_percent: '0.12',
            av_percent: '0.01',
            nnhl_percent: null,
            pl_2_5_percent: '0.00',
            equity: 0,
            pl_a_book: 0,
            pl_lifetime: -391.26,
            pl_today: 0,
            pl_yesterday: 0,
            pl_weekly: 0,
            pl_monthly: -341.73,
            last_equity: 0,
            margin: 0,
            margin_level: 0,
            total_ticket: '375',
            high_leverage_score: '43',
            daily_pl_20_score: '4',
            av_profit_score: '4',
            pl_2_5_score: '0',
            opc_20_score: '0',
            opp_50_score: '0',
            big_lot_score: '0',
            scalper_score: '93',
            slippage_score: '0',
            nnhl_score: '0',
            high_leverage: '11.47 % (43/375)',
            av_profit: '1.07 % (4/375)',
            pl_2_5: '0 % (0/375)',
            scalper: '12.4 % (93/750)',
            slippage: '0 % (0/750)',
            nnhl: '0 % (0/0)',
        },
        {
            code: 'M',
            person_id: 14431,
            person: 'M-14431',
            company: 'Surya',
            name: 'Lioni Surya Sutanto',
            status: 'Aman',
            status_stp: null,
            high_leverage_percent: '0.01',
            slippage_percent: '0.00',
            scalper_percent: '0.11',
            av_percent: '0.00',
            nnhl_percent: '1.00',
            pl_2_5_percent: '0.00',
            equity: 35190.89,
            pl_a_book: 0,
            pl_lifetime: -194656.41,
            pl_today: 0,
            pl_yesterday: 0,
            pl_weekly: -5800.08,
            pl_monthly: 12319.3,
            last_equity: 33684.68,
            margin: 4440,
            margin_level: 792.58761261261,
            total_ticket: '15320',
            high_leverage_score: '192',
            daily_pl_20_score: '24',
            av_profit_score: '44',
            pl_2_5_score: '65',
            opc_20_score: '0',
            opp_50_score: '0',
            big_lot_score: '0',
            scalper_score: '3315',
            slippage_score: '0',
            nnhl_score: '19',
            high_leverage: '1.25 % (192/15320)',
            av_profit: '0.29 % (44/15320)',
            pl_2_5: '0.42 % (65/15320)',
            scalper: '10.82 % (3315/30640)',
            slippage: '0 % (0/30640)',
            nnhl: '50 % (19/38)',
        },
        {
            code: 'M',
            person_id: 69755,
            person: 'M-69755',
            company: 'Surya',
            name: 'PRISSIAN FADLI',
            status: 'Pantau',
            status_stp: null,
            high_leverage_percent: '0.12',
            slippage_percent: '0.00',
            scalper_percent: '0.22',
            av_percent: '0.01',
            nnhl_percent: null,
            pl_2_5_percent: '0.01',
            equity: 24.22,
            pl_a_book: 0,
            pl_lifetime: -358.11,
            pl_today: 0,
            pl_yesterday: 0,
            pl_weekly: -777.23,
            pl_monthly: -209.39,
            last_equity: 24.22,
            margin: 0,
            margin_level: 0,
            total_ticket: '303',
            high_leverage_score: '37',
            daily_pl_20_score: '11',
            av_profit_score: '2',
            pl_2_5_score: '2',
            opc_20_score: '0',
            opp_50_score: '0',
            big_lot_score: '0',
            scalper_score: '136',
            slippage_score: '0',
            nnhl_score: '0',
            high_leverage: '12.21 % (37/303)',
            av_profit: '0.66 % (2/303)',
            pl_2_5: '0.66 % (2/303)',
            scalper: '22.44 % (136/606)',
            slippage: '0 % (0/606)',
            nnhl: '0 % (0/0)',
        },
        {
            code: 'M',
            person_id: 77518,
            person: 'M-77518',
            company: 'Surya',
            name: 'NORIKA',
            status: 'Baru',
            status_stp: null,
            high_leverage_percent: '0.11',
            slippage_percent: '0.00',
            scalper_percent: '0.24',
            av_percent: '0.00',
            nnhl_percent: null,
            pl_2_5_percent: '0.00',
            equity: 0,
            pl_a_book: 0,
            pl_lifetime: -610.88,
            pl_today: 0,
            pl_yesterday: 0,
            pl_weekly: 0,
            pl_monthly: -21.09,
            last_equity: 0,
            margin: 0,
            margin_level: 0,
            total_ticket: '446',
            high_leverage_score: '49',
            daily_pl_20_score: '3',
            av_profit_score: '0',
            pl_2_5_score: '1',
            opc_20_score: '0',
            opp_50_score: '0',
            big_lot_score: '0',
            scalper_score: '211',
            slippage_score: '0',
            nnhl_score: '0',
            high_leverage: '10.99 % (49/446)',
            av_profit: '0 % (0/446)',
            pl_2_5: '0.22 % (1/446)',
            scalper: '23.65 % (211/892)',
            slippage: '0 % (0/892)',
            nnhl: '0 % (0/0)',
        },
        {
            code: 'M',
            person_id: 50735,
            person: 'M-50735',
            company: 'Surya',
            name: 'Heri Kharisma Wijaya',
            status: 'Baru',
            status_stp: null,
            high_leverage_percent: '0.52',
            slippage_percent: '0.00',
            scalper_percent: '0.24',
            av_percent: '0.00',
            nnhl_percent: null,
            pl_2_5_percent: '0.00',
            equity: 0,
            pl_a_book: 0,
            pl_lifetime: -16.17,
            pl_today: 0,
            pl_yesterday: 0,
            pl_weekly: 0,
            pl_monthly: 0,
            last_equity: 0,
            margin: 0,
            margin_level: 0,
            total_ticket: '65',
            high_leverage_score: '34',
            daily_pl_20_score: '4',
            av_profit_score: '0',
            pl_2_5_score: '0',
            opc_20_score: '0',
            opp_50_score: '0',
            big_lot_score: '0',
            scalper_score: '31',
            slippage_score: '0',
            nnhl_score: '0',
            high_leverage: '52.31 % (34/65)',
            av_profit: '0 % (0/65)',
            pl_2_5: '0 % (0/65)',
            scalper: '23.85 % (31/130)',
            slippage: '0 % (0/130)',
            nnhl: '0 % (0/0)',
        },
        {
            code: 'M',
            person_id: 48099,
            person: 'M-48099',
            company: 'Surya',
            name: 'KETHY',
            status: 'Aman',
            status_stp: null,
            high_leverage_percent: '0.00',
            slippage_percent: '0.00',
            scalper_percent: '0.00',
            av_percent: '0.00',
            nnhl_percent: null,
            pl_2_5_percent: '0.00',
            equity: 0,
            pl_a_book: 0,
            pl_lifetime: -313.51,
            pl_today: 0,
            pl_yesterday: 0,
            pl_weekly: -313.51,
            pl_monthly: -313.51,
            last_equity: 0,
            margin: 0,
            margin_level: 0,
            total_ticket: '372',
            high_leverage_score: '0',
            daily_pl_20_score: '2',
            av_profit_score: '1',
            pl_2_5_score: '0',
            opc_20_score: '0',
            opp_50_score: '0',
            big_lot_score: '0',
            scalper_score: '1',
            slippage_score: '0',
            nnhl_score: '0',
            high_leverage: '0 % (0/372)',
            av_profit: '0.27 % (1/372)',
            pl_2_5: '0 % (0/372)',
            scalper: '0.13 % (1/744)',
            slippage: '0 % (0/744)',
            nnhl: '0 % (0/0)',
        },
        {
            code: 'M',
            person_id: 50639,
            person: 'M-50639',
            company: 'Surya',
            name: 'Elon Sibarani',
            status: 'Baru',
            status_stp: null,
            high_leverage_percent: '0.26',
            slippage_percent: '0.01',
            scalper_percent: '0.11',
            av_percent: '0.00',
            nnhl_percent: null,
            pl_2_5_percent: '0.00',
            equity: 1.81,
            pl_a_book: 0,
            pl_lifetime: -133.65,
            pl_today: 0,
            pl_yesterday: 0,
            pl_weekly: 0,
            pl_monthly: 0,
            last_equity: 1.81,
            margin: 0,
            margin_level: 0,
            total_ticket: '477',
            high_leverage_score: '126',
            daily_pl_20_score: '3',
            av_profit_score: '2',
            pl_2_5_score: '0',
            opc_20_score: '0',
            opp_50_score: '0',
            big_lot_score: '0',
            scalper_score: '105',
            slippage_score: '6',
            nnhl_score: '0',
            high_leverage: '26.42 % (126/477)',
            av_profit: '0.42 % (2/477)',
            pl_2_5: '0 % (0/477)',
            scalper: '11.01 % (105/954)',
            slippage: '0.63 % (6/954)',
            nnhl: '0 % (0/0)',
        },
        {
            code: 'M',
            person_id: 10477,
            person: 'M-10477',
            company: 'Surya',
            name: 'Horas Cendana',
            status: 'Aman',
            status_stp: null,
            high_leverage_percent: '0.23',
            slippage_percent: '0.00',
            scalper_percent: '0.10',
            av_percent: '0.01',
            nnhl_percent: null,
            pl_2_5_percent: '0.02',
            equity: 187.34,
            pl_a_book: 0,
            pl_lifetime: 386.4,
            pl_today: 0,
            pl_yesterday: 0,
            pl_weekly: 0,
            pl_monthly: 0,
            last_equity: 187.34,
            margin: 0,
            margin_level: 0,
            total_ticket: '422',
            high_leverage_score: '98',
            daily_pl_20_score: '12',
            av_profit_score: '3',
            pl_2_5_score: '9',
            opc_20_score: '0',
            opp_50_score: '0',
            big_lot_score: '0',
            scalper_score: '84',
            slippage_score: '0',
            nnhl_score: '0',
            high_leverage: '23.22 % (98/422)',
            av_profit: '0.71 % (3/422)',
            pl_2_5: '2.13 % (9/422)',
            scalper: '9.95 % (84/844)',
            slippage: '0 % (0/844)',
            nnhl: '0 % (0/0)',
        },
        {
            code: 'M',
            person_id: 78039,
            person: 'M-78039',
            company: 'Surya',
            name: 'Amin Nawar',
            status: 'Baru',
            status_stp: null,
            high_leverage_percent: '0.20',
            slippage_percent: '0.00',
            scalper_percent: '0.12',
            av_percent: '0.00',
            nnhl_percent: null,
            pl_2_5_percent: '0.00',
            equity: 0,
            pl_a_book: 0,
            pl_lifetime: -257.36,
            pl_today: 0,
            pl_yesterday: 0,
            pl_weekly: 0,
            pl_monthly: 0,
            last_equity: 0,
            margin: 0,
            margin_level: 0,
            total_ticket: '393',
            high_leverage_score: '79',
            daily_pl_20_score: '3',
            av_profit_score: '1',
            pl_2_5_score: '0',
            opc_20_score: '0',
            opp_50_score: '0',
            big_lot_score: '0',
            scalper_score: '94',
            slippage_score: '0',
            nnhl_score: '0',
            high_leverage: '20.1 % (79/393)',
            av_profit: '0.25 % (1/393)',
            pl_2_5: '0 % (0/393)',
            scalper: '11.96 % (94/786)',
            slippage: '0 % (0/786)',
            nnhl: '0 % (0/0)',
        },
        {
            code: 'M',
            person_id: 53337,
            person: 'M-53337',
            company: 'Surya',
            name: 'ANDRE CHRISTIAN',
            status: 'Baru',
            status_stp: null,
            high_leverage_percent: '0.24',
            slippage_percent: '0.00',
            scalper_percent: '0.06',
            av_percent: '0.00',
            nnhl_percent: null,
            pl_2_5_percent: '0.00',
            equity: 16.31,
            pl_a_book: 0,
            pl_lifetime: -275.2,
            pl_today: 0,
            pl_yesterday: 0,
            pl_weekly: 0,
            pl_monthly: 0,
            last_equity: 16.31,
            margin: 0,
            margin_level: 0,
            total_ticket: '288',
            high_leverage_score: '70',
            daily_pl_20_score: '9',
            av_profit_score: '0',
            pl_2_5_score: '0',
            opc_20_score: '0',
            opp_50_score: '0',
            big_lot_score: '0',
            scalper_score: '37',
            slippage_score: '1',
            nnhl_score: '0',
            high_leverage: '24.31 % (70/288)',
            av_profit: '0 % (0/288)',
            pl_2_5: '0 % (0/288)',
            scalper: '6.42 % (37/576)',
            slippage: '0.17 % (1/576)',
            nnhl: '0 % (0/0)',
        },
        {
            code: 'M',
            person_id: 69194,
            person: 'M-69194',
            company: 'Surya',
            name: 'Richard Chally Luhulima',
            status: 'Baru',
            status_stp: null,
            high_leverage_percent: '0.27',
            slippage_percent: '0.00',
            scalper_percent: '0.17',
            av_percent: '0.01',
            nnhl_percent: null,
            pl_2_5_percent: '0.00',
            equity: 617.07,
            pl_a_book: 0,
            pl_lifetime: -162.58,
            pl_today: 0,
            pl_yesterday: 0,
            pl_weekly: 0,
            pl_monthly: -31.68,
            last_equity: 617.07,
            margin: 0,
            margin_level: 0,
            total_ticket: '663',
            high_leverage_score: '182',
            daily_pl_20_score: '0',
            av_profit_score: '7',
            pl_2_5_score: '0',
            opc_20_score: '0',
            opp_50_score: '0',
            big_lot_score: '0',
            scalper_score: '232',
            slippage_score: '0',
            nnhl_score: '0',
            high_leverage: '27.45 % (182/663)',
            av_profit: '1.06 % (7/663)',
            pl_2_5: '0 % (0/663)',
            scalper: '17.5 % (232/1326)',
            slippage: '0 % (0/1326)',
            nnhl: '0 % (0/0)',
        },
        {
            code: 'M',
            person_id: 10798,
            person: 'M-10798',
            company: 'Surya',
            name: 'I Made Astawa',
            status: 'Baru',
            status_stp: null,
            high_leverage_percent: '0.55',
            slippage_percent: '0.00',
            scalper_percent: '0.31',
            av_percent: '0.00',
            nnhl_percent: null,
            pl_2_5_percent: '0.00',
            equity: 434.46,
            pl_a_book: 0,
            pl_lifetime: -280.7,
            pl_today: 0,
            pl_yesterday: 0,
            pl_weekly: -160.3,
            pl_monthly: -229.25,
            last_equity: 434.46,
            margin: 0,
            margin_level: 0,
            total_ticket: '73',
            high_leverage_score: '40',
            daily_pl_20_score: '2',
            av_profit_score: '0',
            pl_2_5_score: '0',
            opc_20_score: '0',
            opp_50_score: '0',
            big_lot_score: '0',
            scalper_score: '45',
            slippage_score: '0',
            nnhl_score: '0',
            high_leverage: '54.79 % (40/73)',
            av_profit: '0 % (0/73)',
            pl_2_5: '0 % (0/73)',
            scalper: '30.82 % (45/146)',
            slippage: '0 % (0/146)',
            nnhl: '0 % (0/0)',
        },
    ],
    first_page_url: 'https://rpt-rm-dev.surya-am.com/api/v1/tra?per_page=15&page=1',
    from: 1,
    last_page: 679,
    last_page_url: 'https://rpt-rm-dev.surya-am.com/api/v1/tra?per_page=15&page=679',
    links: [
        {
            url: null,
            label: '&laquo; Previous',
            active: false,
        },
        {
            url: 'https://rpt-rm-dev.surya-am.com/api/v1/tra?per_page=15&page=1',
            label: '1',
            active: true,
        },
        {
            url: 'https://rpt-rm-dev.surya-am.com/api/v1/tra?per_page=15&page=2',
            label: '2',
            active: false,
        },
        {
            url: 'https://rpt-rm-dev.surya-am.com/api/v1/tra?per_page=15&page=3',
            label: '3',
            active: false,
        },
        {
            url: 'https://rpt-rm-dev.surya-am.com/api/v1/tra?per_page=15&page=4',
            label: '4',
            active: false,
        },
        {
            url: 'https://rpt-rm-dev.surya-am.com/api/v1/tra?per_page=15&page=5',
            label: '5',
            active: false,
        },
        {
            url: 'https://rpt-rm-dev.surya-am.com/api/v1/tra?per_page=15&page=6',
            label: '6',
            active: false,
        },
        {
            url: 'https://rpt-rm-dev.surya-am.com/api/v1/tra?per_page=15&page=7',
            label: '7',
            active: false,
        },
        {
            url: 'https://rpt-rm-dev.surya-am.com/api/v1/tra?per_page=15&page=8',
            label: '8',
            active: false,
        },
        {
            url: 'https://rpt-rm-dev.surya-am.com/api/v1/tra?per_page=15&page=9',
            label: '9',
            active: false,
        },
        {
            url: 'https://rpt-rm-dev.surya-am.com/api/v1/tra?per_page=15&page=10',
            label: '10',
            active: false,
        },
        {
            url: null,
            label: '...',
            active: false,
        },
        {
            url: 'https://rpt-rm-dev.surya-am.com/api/v1/tra?per_page=15&page=678',
            label: '678',
            active: false,
        },
        {
            url: 'https://rpt-rm-dev.surya-am.com/api/v1/tra?per_page=15&page=679',
            label: '679',
            active: false,
        },
        {
            url: 'https://rpt-rm-dev.surya-am.com/api/v1/tra?per_page=15&page=2',
            label: 'Next &raquo;',
            active: false,
        },
    ],
    next_page_url: 'https://rpt-rm-dev.surya-am.com/api/v1/tra?per_page=15&page=2',
    path: 'https://rpt-rm-dev.surya-am.com/api/v1/tra',
    per_page: 15,
    prev_page_url: null,
    to: 15,
    total: 10184,
};

module.exports = data;
