var data = {
    current_page: 1,
    data: [
        {
            code: 'M',
            person_id: 2927,
            person: 'M-2927',
            company: 'Surya',
            name: 'load test 4',
            status: 'Baru',
            status_stp: null,
            high_leverage_percent: '0.00',
            slippage_percent: '0.00',
            scalper_percent: '0.00',
            av_percent: '0.00',
            nnhl_percent: null,
            pl_2_5_percent: '0.06',
            equity: 0,
            pl_a_book: 0,
            pl_lifetime: -6721.68,
            pl_today: 0,
            pl_yesterday: 0.31,
            pl_weekly: 0,
            pl_monthly: 0,
            last_equity: 60544.77,
            margin: 0,
            margin_level: 0,
            total_ticket: '17',
            high_leverage_score: '0',
            daily_pl_20_score: '0',
            av_profit_score: '0',
            pl_2_5_score: '1',
            opc_20_score: '0',
            opp_50_score: '0',
            big_lot_score: '0',
            scalper_score: '0',
            slippage_score: '0',
            nnhl_score: '0',
            high_leverage: '0 % (0/17)',
            av_profit: '0 % (0/17)',
            pl_2_5: '5.88 % (1/17)',
            scalper: '0 % (0/34)',
            slippage: '0 % (0/34)',
            nnhl: '0 % (0/0)',
        },
        {
            code: 'M',
            person_id: 54077,
            person: 'M-54077',
            company: 'Surya',
            name: 'RICHARD MARK',
            status: 'Pantau',
            status_stp: null,
            high_leverage_percent: '0.29',
            slippage_percent: '0.00',
            scalper_percent: '0.15',
            av_percent: '0.02',
            nnhl_percent: null,
            pl_2_5_percent: '0.00',
            equity: 0,
            pl_a_book: 0,
            pl_lifetime: -240.16,
            pl_today: 0,
            pl_yesterday: 0,
            pl_weekly: 0,
            pl_monthly: 0,
            last_equity: 0,
            margin: 0,
            margin_level: 0,
            total_ticket: '731',
            high_leverage_score: '211',
            daily_pl_20_score: '7',
            av_profit_score: '11',
            pl_2_5_score: '1',
            opc_20_score: '0',
            opp_50_score: '0',
            big_lot_score: '0',
            scalper_score: '213',
            slippage_score: '6',
            nnhl_score: '0',
            high_leverage: '28.86 % (211/731)',
            av_profit: '1.5 % (11/731)',
            pl_2_5: '0.14 % (1/731)',
            scalper: '14.57 % (213/1462)',
            slippage: '0.41 % (6/1462)',
            nnhl: '0 % (0/0)',
        },
        {
            code: 'M',
            person_id: 77028,
            person: 'M-77028',
            company: 'Surya',
            name: 'Muhammad Fadhillah Putra ST',
            status: 'Baru',
            status_stp: null,
            high_leverage_percent: '0.32',
            slippage_percent: '0.00',
            scalper_percent: '0.27',
            av_percent: '0.00',
            nnhl_percent: null,
            pl_2_5_percent: '0.00',
            equity: 0,
            pl_a_book: 0,
            pl_lifetime: -413.73,
            pl_today: 0,
            pl_yesterday: 0,
            pl_weekly: 0,
            pl_monthly: 0,
            last_equity: 0,
            margin: 0,
            margin_level: 0,
            total_ticket: '232',
            high_leverage_score: '75',
            daily_pl_20_score: '0',
            av_profit_score: '1',
            pl_2_5_score: '1',
            opc_20_score: '0',
            opp_50_score: '0',
            big_lot_score: '0',
            scalper_score: '126',
            slippage_score: '0',
            nnhl_score: '0',
            high_leverage: '32.33 % (75/232)',
            av_profit: '0.43 % (1/232)',
            pl_2_5: '0.43 % (1/232)',
            scalper: '27.16 % (126/464)',
            slippage: '0 % (0/464)',
            nnhl: '0 % (0/0)',
        },
        {
            code: 'M',
            person_id: 83194,
            person: 'M-83194',
            company: 'Surya',
            name: 'Mike Lim',
            status: 'Baru',
            status_stp: null,
            high_leverage_percent: '0.11',
            slippage_percent: '0.00',
            scalper_percent: '0.12',
            av_percent: '0.01',
            nnhl_percent: null,
            pl_2_5_percent: '0.00',
            equity: 0,
            pl_a_book: 0,
            pl_lifetime: -391.26,
            pl_today: 0,
            pl_yesterday: 0,
            pl_weekly: 0,
            pl_monthly: -341.73,
            last_equity: 0,
            margin: 0,
            margin_level: 0,
            total_ticket: '375',
            high_leverage_score: '43',
            daily_pl_20_score: '4',
            av_profit_score: '4',
            pl_2_5_score: '0',
            opc_20_score: '0',
            opp_50_score: '0',
            big_lot_score: '0',
            scalper_score: '93',
            slippage_score: '0',
            nnhl_score: '0',
            high_leverage: '11.47 % (43/375)',
            av_profit: '1.07 % (4/375)',
            pl_2_5: '0 % (0/375)',
            scalper: '12.4 % (93/750)',
            slippage: '0 % (0/750)',
            nnhl: '0 % (0/0)',
        },
        {
            code: 'M',
            person_id: 14431,
            person: 'M-14431',
            company: 'Surya',
            name: 'Lioni Surya Sutanto',
            status: 'Aman',
            status_stp: null,
            high_leverage_percent: '0.01',
            slippage_percent: '0.00',
            scalper_percent: '0.11',
            av_percent: '0.00',
            nnhl_percent: '1.00',
            pl_2_5_percent: '0.00',
            equity: 35190.89,
            pl_a_book: 0,
            pl_lifetime: -194656.41,
            pl_today: 0,
            pl_yesterday: 0,
            pl_weekly: -5800.08,
            pl_monthly: 12319.3,
            last_equity: 33684.68,
            margin: 4440,
            margin_level: 792.58761261261,
            total_ticket: '15320',
            high_leverage_score: '192',
            daily_pl_20_score: '24',
            av_profit_score: '44',
            pl_2_5_score: '65',
            opc_20_score: '0',
            opp_50_score: '0',
            big_lot_score: '0',
            scalper_score: '3315',
            slippage_score: '0',
            nnhl_score: '19',
            high_leverage: '1.25 % (192/15320)',
            av_profit: '0.29 % (44/15320)',
            pl_2_5: '0.42 % (65/15320)',
            scalper: '10.82 % (3315/30640)',
            slippage: '0 % (0/30640)',
            nnhl: '50 % (19/38)',
        },
    ],
    first_page_url: 'https://rpt-rm-dev.surya-am.com/api/v1/tra?per_page=15&page=1',
    from: 1,
    last_page: 679,
    last_page_url: 'https://rpt-rm-dev.surya-am.com/api/v1/tra?per_page=15&page=679',
    links: [
        {
            url: null,
            label: '&laquo; Previous',
            active: false,
        },
        {
            url: 'https://rpt-rm-dev.surya-am.com/api/v1/tra?per_page=15&page=1',
            label: '1',
            active: true,
        },
        {
            url: 'https://rpt-rm-dev.surya-am.com/api/v1/tra?per_page=15&page=2',
            label: '2',
            active: false,
        },
        {
            url: 'https://rpt-rm-dev.surya-am.com/api/v1/tra?per_page=15&page=3',
            label: '3',
            active: false,
        },
        {
            url: 'https://rpt-rm-dev.surya-am.com/api/v1/tra?per_page=15&page=4',
            label: '4',
            active: false,
        },
        {
            url: 'https://rpt-rm-dev.surya-am.com/api/v1/tra?per_page=15&page=5',
            label: '5',
            active: false,
        },
        {
            url: 'https://rpt-rm-dev.surya-am.com/api/v1/tra?per_page=15&page=6',
            label: '6',
            active: false,
        },
        {
            url: 'https://rpt-rm-dev.surya-am.com/api/v1/tra?per_page=15&page=7',
            label: '7',
            active: false,
        },
        {
            url: 'https://rpt-rm-dev.surya-am.com/api/v1/tra?per_page=15&page=8',
            label: '8',
            active: false,
        },
        {
            url: 'https://rpt-rm-dev.surya-am.com/api/v1/tra?per_page=15&page=9',
            label: '9',
            active: false,
        },
        {
            url: 'https://rpt-rm-dev.surya-am.com/api/v1/tra?per_page=15&page=10',
            label: '10',
            active: false,
        },
        {
            url: null,
            label: '...',
            active: false,
        },
        {
            url: 'https://rpt-rm-dev.surya-am.com/api/v1/tra?per_page=15&page=678',
            label: '678',
            active: false,
        },
        {
            url: 'https://rpt-rm-dev.surya-am.com/api/v1/tra?per_page=15&page=679',
            label: '679',
            active: false,
        },
        {
            url: 'https://rpt-rm-dev.surya-am.com/api/v1/tra?per_page=15&page=2',
            label: 'Next &raquo;',
            active: false,
        },
    ],
    next_page_url: 'https://rpt-rm-dev.surya-am.com/api/v1/tra?per_page=15&page=2',
    path: 'https://rpt-rm-dev.surya-am.com/api/v1/tra',
    per_page: 15,
    prev_page_url: null,
    to: 15,
    total: 10184,
};

module.exports = data;
