var data = [
    {
        server: 'Surya',
        account: 99164723,
        alert_type: 'Mahi - 30s',
        severity: 'Critical',
        created_at: '2023-11-22 06:05:18',
        checked_by: 'Kiki',
        checked_at: '2023-11-23 14:38:29',
        status: 'Bahaya',
        status_stp: 'A-Book',
        rec_status: 'Bahaya',
        rec_status_stp: 'A-Book',
        events: ['Mahi - 30s', 'Mahi - 120s', 'Group Trade', 'PL Yesterday', 'PL Change'],
    },
    {
        server: 'Valutrades',
        account: 49009846,
        alert_type: 'Mahi - 30s',
        severity: 'Critical',
        created_at: '2023-11-24 10:15:32',
        checked_by: 'Kiki',
        checked_at: '2023-11-25 18:09:54',
        status: 'Bahaya',
        status_stp: 'B-Book',
        rec_status: 'Bahaya',
        rec_status_stp: 'A-Book',
        events: ['Mahi - 30s', 'Big lot', 'Group Trade', 'PL Change', 'Big lot'],
    },
    {
        server: 'Surya',
        account: 87583210,
        alert_type: 'Biglot',
        severity: 'Critical',
        created_at: '2023-11-25 18:45:57',
        checked_by: 'Kiki',
        checked_at: '2023-11-26 22:31:12',
        status: 'Bahaya',
        status_stp: 'A-Book',
        rec_status: 'Bahaya',
        rec_status_stp: 'A-Book',
        events: ['Mahi - 120s', 'Big Lot', 'Group Trade', 'PL Change', 'Big lot'],
    },
    {
        server: 'Valutrades',
        account: 67258309,
        alert_type: 'Mahi - 30s',
        severity: 'Critical',
        created_at: '2023-11-26 07:32:12',
        checked_by: 'Kipli',
        checked_at: '2023-11-27 10:47:18',
        status: 'Bahaya',
        status_stp: 'A-Book',
        rec_status: 'Bahaya',
        rec_status_stp: 'A-Book',
        events: ['Mahi - 30s', 'Mahi - 120s', 'Group Trade', 'PL Change'],
    },
    {
        server: 'Surya',
        account: 75260139,
        alert_type: 'Mahi - 30s',
        severity: 'Critical',
        created_at: '2023-11-23 13:57:41',
        checked_by: 'Kiki',
        checked_at: '2023-11-24 09:32:55',
        status: 'Bahaya',
        status_stp: 'B-Book',
        rec_status: 'Bahaya',
        rec_status_stp: 'A-Book',
        events: ['Mahi - 30s', 'Mahi - 120s', 'Group Trade', 'PL Change'],
    },
    {
        server: 'Valutrades',
        account: 30045125,
        alert_type: 'Biglot',
        severity: 'Critical',
        created_at: '2023-11-26 21:06:05',
        checked_by: 'Kipli',
        checked_at: '2023-11-27 16:59:22',
        status: 'Bahaya',
        status_stp: 'A-Book',
        rec_status: 'Bahaya',
        rec_status_stp: 'A-Book',
        events: ['Mahi - 30s', 'Mahi - 120s', 'Group Trade', 'PL Change'],
    },
    {
        server: 'Surya',
        account: 27543168,
        alert_type: 'Mahi - 30s',
        severity: 'Critical',
        created_at: '2023-11-23 09:24:29',
        checked_by: 'Kipli',
        checked_at: '2023-11-24 14:29:47',
        status: 'Bahaya',
        status_stp: 'A-Book',
        rec_status: 'Bahaya',
        rec_status_stp: 'A-Book',
        events: ['Mahi - 30s', 'Mahi - 120s', 'Group Trade', 'PL Change'],
    },
    {
        server: 'Valutrades',
        account: 95806426,
        alert_type: 'EOD Trading',
        severity: 'Critical',
        created_at: '2023-11-26 03:40:57',
        checked_by: 'Kiki',
        checked_at: '2023-11-27 08:19:03',
        status: 'Bahaya',
        status_stp: 'A-Book',
        rec_status: 'Bahaya',
        rec_status_stp: 'A-Book',
        events: ['Mahi - 30s', 'Mahi - 120s', 'Group Trade', 'PL Change'],
    },
    {
        server: 'Surya',
        account: 30075319,
        alert_type: 'Mahi - 30s',
        severity: 'Critical',
        created_at: '2023-11-25 15:12:09',
        checked_by: 'Kiki',
        checked_at: '2023-11-26 11:25:52',
        status: 'Bahaya',
        status_stp: 'A-Book',
        rec_status: 'Bahaya',
        rec_status_stp: 'A-Book',
        events: ['Mahi - 30s', 'Mahi - 120s', 'Group Trade', 'PL Change'],
    },
    {
        server: 'Valutrades',
        account: 62541382,
        alert_type: 'Mahi - 30s',
        severity: 'Critical',
        created_at: '2023-11-24 19:03:47',
        checked_by: 'Kiki',
        checked_at: '2023-11-26 09:48:34',
        status: 'Bahaya',
        status_stp: 'A-Book',
        rec_status: 'Bahaya',
        rec_status_stp: 'A-Book',
        events: ['Mahi - 30s', 'Mahi - 120s', 'Group Trade', 'PL Change'],
    },
    {
        server: 'Surya',
        account: 84657123,
        alert_type: 'Mahi - 30s',
        severity: 'Critical',
        created_at: '2023-11-25 07:29:14',
        checked_by: 'Kaplak',
        checked_at: '2023-11-26 10:05:57',
        status: 'Bahaya',
        status_stp: 'A-Book',
        rec_status: 'Bahaya',
        rec_status_stp: 'A-Book',
        events: ['Mahi - 30s', 'Mahi - 120s', 'Group Trade', 'PL Change'],
    },
    {
        server: 'Valutrades',
        account: 68238546,
        alert_type: 'Profit 1%',
        severity: 'High',
        created_at: '2023-11-23 14:20:59',
        checked_by: 'Kiki',
        checked_at: '2023-11-24 11:18:21',
        status: 'Pantau',
        status_stp: 'A-Book',
        rec_status: 'Bahaya',
        rec_status_stp: 'A-Book',
        events: ['Mahi - 30s', 'Mahi - 120s', 'Group Trade', 'PL Change'],
    },
    {
        server: 'Surya',
        account: 79826546,
        alert_type: 'Profit 1%',
        severity: 'High',
        created_at: '2023-11-25 09:46:27',
        checked_by: 'Kiki',
        checked_at: '2023-11-26 13:28:59',
        status: 'Aman',
        status_stp: 'A-Book',
        rec_status: 'Bahaya',
        rec_status_stp: 'A-Book',
        events: ['Mahi - 30s', 'Mahi - 120s', 'Group Trade', 'PL Change'],
    },
    {
        server: 'Valutrades',
        account: 42208316,
        alert_type: 'Biglot',
        severity: 'High',
        created_at: '2023-11-25 20:59:34',
        checked_by: 'Kaplak',
        checked_at: '2023-11-27 01:47:41',
        status: 'Bahaya',
        status_stp: 'A-Book',
        rec_status: 'Bahaya',
        rec_status_stp: 'A-Book',
        events: ['Mahi - 30s', 'Mahi - 120s', 'Group Trade', 'PL Change'],
    },
    {
        server: 'Surya',
        account: 30457968,
        alert_type: 'AV Profit',
        severity: 'High',
        created_at: '2023-11-26 11:37:48',
        checked_by: 'Kipli',
        checked_at: '2023-11-27 14:10:52',
        status: 'Pantau',
        status_stp: 'A-Book',
        rec_status: 'Bahaya',
        rec_status_stp: 'A-Book',
        events: ['Mahi - 30s', 'Mahi - 120s', 'Group Trade', 'PL Change'],
    },
    {
        server: 'Valutrades',
        account: 14905347,
        alert_type: 'Profit 1%',
        severity: 'High',
        created_at: '2023-11-24 17:14:56',
        checked_by: 'Kiki',
        checked_at: '2023-11-25 20:03:10',
        status: 'Aman',
        status_stp: 'A-Book',
        rec_status: 'Bahaya',
        rec_status_stp: 'A-Book',
        events: ['Mahi - 30s', 'Mahi - 120s', 'Group Trade', 'PL Change'],
    },
    {
        server: 'Surya',
        account: 69087316,
        alert_type: 'AV Profit',
        severity: 'High',
        created_at: '2023-11-26 08:55:23',
        checked_by: 'Kiki',
        checked_at: '2023-11-27 12:06:37',
        status: 'Bahaya',
        status_stp: 'A-Book',
        rec_status: 'Bahaya',
        rec_status_stp: 'A-Book',
        events: ['Mahi - 30s', 'Mahi - 120s', 'Group Trade', 'PL Change'],
    },
    {
        server: 'Valutrades',
        account: 72897048,
        alert_type: 'EOD Trading',
        severity: 'High',
        created_at: '2023-11-25 15:06:39',
        checked_by: 'Kiki',
        checked_at: '2023-11-26 22:15:47',
        status: 'Pantau',
        status_stp: 'A-Book',
        rec_status: 'Bahaya',
        rec_status_stp: 'A-Book',
        events: ['Mahi - 30s', 'Mahi - 120s', 'Group Trade', 'PL Change'],
    },
    {
        server: 'Surya',
        account: 47361985,
        alert_type: 'Profit 1%',
        severity: 'High',
        created_at: '2023-11-23 12:53:47',
        checked_by: 'Kiki',
        checked_at: '2023-11-24 14:11:53',
        status: 'Aman',
        status_stp: 'A-Book',
        rec_status: 'Bahaya',
        rec_status_stp: 'A-Book',
        events: ['Mahi - 30s', 'Mahi - 120s', 'Group Trade', 'PL Change'],
    },
    {
        server: 'Valutrades',
        account: 53671982,
        alert_type: '50% OPP',
        severity: 'High',
        created_at: '2023-11-26 06:41:52',
        checked_by: 'Kipli',
        checked_at: '2023-11-27 04:18:18',
        status: 'Bahaya',
        status_stp: 'A-Book',
        rec_status: 'Bahaya',
        rec_status_stp: 'A-Book',
        events: ['Mahi - 30s', 'Mahi - 120s', 'Group Trade', 'PL Change'],
    },
    {
        server: 'Surya',
        account: 23819657,
        alert_type: 'Profit 1%',
        severity: 'High',
        created_at: '2023-11-24 23:19:04',
        checked_by: 'Kiki',
        checked_at: '2023-11-26 06:01:23',
        status: 'Pantau',
        status_stp: 'A-Book',
        rec_status: 'Bahaya',
        rec_status_stp: 'A-Book',
        events: ['Mahi - 30s', 'Mahi - 120s', 'Group Trade', 'PL Change'],
    },
    {
        server: 'Valutrades',
        account: 89462718,
        alert_type: 'Biglot',
        severity: 'High',
        created_at: '2023-11-26 01:02:18',
        checked_by: 'Kiki',
        checked_at: '2023-11-27 05:18:29',
        status: 'Aman',
        status_stp: 'A-Book',
        rec_status: 'Bahaya',
        rec_status_stp: 'A-Book',
        events: ['Mahi - 30s', 'Mahi - 120s', 'Group Trade', 'PL Change'],
    },
    {
        server: 'Surya',
        account: 78546921,
        alert_type: 'Profit 1%',
        severity: 'High',
        created_at: '2023-11-24 09:48:34',
        checked_by: 'Kiki',
        checked_at: '2023-11-25 17:29:47',
        status: 'Bahaya',
        status_stp: 'A-Book',
        rec_status: 'Bahaya',
        rec_status_stp: 'A-Book',
        events: ['Mahi - 30s', 'Mahi - 120s', 'Group Trade', 'PL Change'],
    },
    {
        server: 'Valutrades',
        account: 64138926,
        alert_type: 'Profit 1%',
        severity: 'High',
        created_at: '2023-11-25 16:35:42',
        checked_by: 'Kiki',
        checked_at: '2023-11-27 00:49:03',
        status: 'Pantau',
        status_stp: 'A-Book',
        rec_status: 'Bahaya',
        rec_status_stp: 'A-Book',
        events: ['Mahi - 30s', 'Mahi - 120s', 'Group Trade', 'PL Change'],
    },
    {
        server: 'Surya',
        account: 96854012,
        alert_type: 'EOD Trading',
        severity: 'High',
        created_at: '2023-11-24 05:27:55',
        checked_by: 'Kipli',
        checked_at: '2023-11-25 09:14:27',
        status: 'Aman',
        status_stp: 'A-Book',
        rec_status: 'Bahaya',
        rec_status_stp: 'A-Book',
        events: ['Mahi - 30s', 'Mahi - 120s', 'Group Trade', 'PL Change'],
    },
    {
        server: 'Valutrades',
        account: 68132095,
        alert_type: 'AV Profit',
        severity: 'High',
        created_at: '2023-11-26 18:59:07',
        checked_by: 'Kiki',
        checked_at: '2023-11-27 19:48:42',
        status: 'Bahaya',
        status_stp: 'A-Book',
        rec_status: 'Bahaya',
        rec_status_stp: 'A-Book',
        events: ['Mahi - 30s', 'Mahi - 120s', 'Group Trade', 'PL Change'],
    },
    {
        server: 'Surya',
        account: 72946135,
        alert_type: 'Profit 1%',
        severity: 'High',
        created_at: '2023-11-23 16:42:14',
        checked_by: 'Kipli',
        checked_at: '2023-11-24 17:29:57',
        status: 'Pantau',
        status_stp: 'A-Book',
        rec_status: 'Bahaya',
        rec_status_stp: 'A-Book',
        events: ['Mahi - 30s', 'Mahi - 120s', 'Group Trade', 'PL Change'],
    },
    {
        server: 'Surya',
        account: 73829641,
        alert_type: 'Profit 1%',
        severity: 'Medium',
        created_at: '2023-11-23 09:50:14',
        checked_by: 'Kiki',
        checked_at: '2023-11-24 12:05:56',
        status: 'Aman',
        status_stp: 'A-Book',
        rec_status: 'Bahaya',
        rec_status_stp: 'A-Book',
        events: ['Mahi - 30s', 'Mahi - 120s', 'Group Trade', 'PL Change'],
    },
    {
        server: 'Valutrades',
        account: 50291384,
        alert_type: 'EOD Trading',
        severity: 'Medium',
        created_at: '2023-11-25 22:37:22',
        checked_by: 'Kiki',
        checked_at: '2023-11-27 01:32:38',
        status: 'Bahaya',
        status_stp: 'A-Book',
        rec_status: 'Bahaya',
        rec_status_stp: 'A-Book',
        events: ['Mahi - 30s', 'Mahi - 120s', 'Group Trade', 'PL Change'],
    },
    {
        server: 'Surya',
        account: 31429876,
        alert_type: '50% OPP',
        severity: 'Medium',
        created_at: '2023-11-25 18:14:59',
        checked_by: 'Kipli',
        checked_at: '2023-11-26 21:52:05',
        status: 'Pantau',
        status_stp: 'A-Book',
        rec_status: 'Bahaya',
        rec_status_stp: 'A-Book',
        events: ['Mahi - 30s', 'Mahi - 120s', 'Group Trade', 'PL Change'],
    },
    {
        server: 'Valutrades',
        account: 69385079,
        alert_type: 'EOD Trading',
        severity: 'Medium',
        created_at: '2023-11-26 10:32:18',
        checked_by: 'Kiki',
        checked_at: '2023-11-27 09:51:26',
        status: 'Aman',
        status_stp: 'A-Book',
        rec_status: 'Bahaya',
        rec_status_stp: 'A-Book',
        events: ['Mahi - 30s', 'Mahi - 120s', 'Group Trade', 'PL Change'],
    },
    {
        server: 'Surya',
        account: 17623894,
        alert_type: 'Profit 1%',
        severity: 'Medium',
        created_at: '2023-11-24 17:57:34',
        checked_by: 'Kiki',
        checked_at: '2023-11-26 01:38:48',
        status: 'Bahaya',
        status_stp: 'A-Book',
        rec_status: 'Bahaya',
        rec_status_stp: 'A-Book',
        events: ['Mahi - 30s', 'Mahi - 120s', 'Group Trade', 'PL Change'],
    },
    {
        server: 'Valutrades',
        account: 81263945,
        alert_type: 'Biglot',
        severity: 'Medium',
        created_at: '2023-11-26 04:25:56',
        checked_by: 'Kiki',
        checked_at: '2023-11-27 08:58:20',
        status: 'Pantau',
        status_stp: 'A-Book',
        rec_status: 'Bahaya',
        rec_status_stp: 'A-Book',
        events: ['Mahi - 30s', 'Mahi - 120s', 'Group Trade', 'PL Change'],
    },
    {
        server: 'Surya',
        account: 65983204,
        alert_type: 'Profit 1%',
        severity: 'Medium',
        created_at: '2023-11-25 11:18:08',
        checked_by: 'Kiki',
        checked_at: '2023-11-26 22:27:09',
        status: 'Aman',
        status_stp: 'A-Book',
        rec_status: 'Bahaya',
        rec_status_stp: 'A-Book',
        events: ['Mahi - 30s', 'Mahi - 120s', 'Group Trade', 'PL Change'],
    },
    {
        server: 'Valutrades',
        account: 40958723,
        alert_type: 'EOD Trading',
        severity: 'Medium',
        created_at: '2023-11-23 07:29:33',
        checked_by: 'Kiki',
        checked_at: '2023-11-24 11:07:42',
        status: 'Bahaya',
        status_stp: 'A-Book',
        rec_status: 'Bahaya',
        rec_status_stp: 'A-Book',
        events: ['Mahi - 30s', 'Mahi - 120s', 'Group Trade', 'PL Change'],
    },
    {
        server: 'Surya',
        account: 59648235,
        alert_type: 'Profit 1%',
        severity: 'Medium',
        created_at: '2023-11-26 02:06:47',
        checked_by: 'Kiki',
        checked_at: '2023-11-27 06:19:21',
        status: 'Pantau',
        status_stp: 'A-Book',
        rec_status: 'Bahaya',
        rec_status_stp: 'A-Book',
        events: ['Mahi - 30s', 'Mahi - 120s', 'Group Trade', 'PL Change'],
    },
    {
        server: 'Valutrades',
        account: 28239765,
        alert_type: 'AV Profit',
        severity: 'Medium',
        created_at: '2023-11-24 10:51:51',
        checked_by: 'Kiki',
        checked_at: '2023-11-26 12:57:24',
        status: 'Aman',
        status_stp: 'A-Book',
        rec_status: 'Bahaya',
        rec_status_stp: 'A-Book',
        events: ['Mahi - 30s', 'Mahi - 120s', 'Group Trade', 'PL Change'],
    },
    {
        server: 'Surya',
        account: 71649520,
        alert_type: 'Profit 1%',
        severity: 'Medium',
        created_at: '2023-11-25 15:40:07',
        checked_by: 'Kiki',
        checked_at: '2023-11-26 18:31:56',
        status: 'Bahaya',
        status_stp: 'A-Book',
        rec_status: 'Bahaya',
        rec_status_stp: 'A-Book',
        events: ['Mahi - 30s', 'Mahi - 120s', 'Group Trade', 'PL Change'],
    },
    {
        server: 'Valutrades',
        account: 85467029,
        alert_type: '50% OPP',
        severity: 'Medium',
        created_at: '2023-11-24 19:28:16',
        checked_by: 'Kiki',
        checked_at: '2023-11-25 22:35:19',
        status: 'Pantau',
        status_stp: 'A-Book',
        rec_status: 'Bahaya',
        rec_status_stp: 'A-Book',
        events: ['Mahi - 30s', 'Mahi - 120s', 'Group Trade', 'PL Change'],
    },
    {
        server: 'Surya',
        account: 65398271,
        alert_type: 'Profit 1%',
        severity: 'Medium',
        created_at: '2023-11-25 04:07:22',
        checked_by: 'Kiki',
        checked_at: '2023-11-26 08:46:53',
        status: 'Aman',
        status_stp: 'A-Book',
        rec_status: 'Bahaya',
        rec_status_stp: 'A-Book',
        events: ['Mahi - 30s', 'Mahi - 120s', 'Group Trade', 'PL Change'],
    },
    {
        server: 'Valutrades',
        account: 49638102,
        alert_type: 'Biglot',
        severity: 'Medium',
        created_at: '2023-11-24 01:53:30',
        checked_by: 'Kiki',
        checked_at: '2023-11-25 09:28:49',
        status: 'Bahaya',
        status_stp: 'A-Book',
        rec_status: 'Bahaya',
        rec_status_stp: 'A-Book',
        events: ['Mahi - 30s', 'Mahi - 120s', 'Group Trade', 'PL Change'],
    },
    {
        server: 'Surya',
        account: 43790168,
        alert_type: 'EOD Trading',
        severity: 'Medium',
        created_at: '2023-11-26 07:14:45',
        checked_by: 'Kipli',
        checked_at: '2023-11-27 12:06:55',
        status: 'Pantau',
        status_stp: 'A-Book',
        rec_status: 'Bahaya',
        rec_status_stp: 'A-Book',
        events: ['Mahi - 30s', 'Mahi - 120s', 'Group Trade', 'PL Change'],
    },
    {
        server: 'Valutrades',
        account: 92085643,
        alert_type: 'Profit 1%',
        severity: 'Medium',
        created_at: '2023-11-23 13:42:56',
        checked_by: 'Kipli',
        checked_at: '2023-11-24 14:54:14',
        status: 'Bahaya',
        status_stp: 'A-Book',
        rec_status: 'Bahaya',
        rec_status_stp: 'A-Book',
        events: ['Mahi - 30s', 'Mahi - 120s', 'Group Trade', 'PL Change'],
    },
    {
        server: 'Valutrades',
        account: 92085643,
        alert_type: 'Profit 1%',
        severity: 'Medium',
        created_at: '2023-11-23 13:42:56',
        checked_by: 'Kipli',
        checked_at: '2023-11-24 14:54:14',
        status: 'Pantau',
        status_stp: 'A-Book',
        rec_status: 'Bahaya',
        rec_status_stp: 'A-Book',
        events: ['Mahi - 30s', 'Mahi - 120s', 'Group Trade', 'PL Change'],
    },
];

module.exports = data;
