var data = {
  "current_page": 1,
  "data": [
      {
          "name": "dummy",
          "server": "MT4IN4",
          "login": 1117140,
          "total_ticket": 0,
          "equity": 0,
          "currency": "USD",
          "ma_date": null,
          "opc_20": 0,
          "opp_50": 0,
          "daily_pl_20": 0,
          "mr": 0,
          "mr_percent": 0,
          "big_lot": 0,
          "last_equity": 0,
          "nnhl": null,
          "nnhl_score": 0,
          "nnhl_percent": 0,
          "av_profit_score": 0,
          "av_percent": null,
          "av_profit": "0.00% (0/)",
          "high_leverage_score": 0,
          "high_leverage_percent": null,
          "high_leverage": "0.00% (0/)",
          "pl_2_5_score": 0,
          "pl_2_5_percent": null,
          "pl_2_5": "0.00% (0/)",
          "pl_change": null,
          "pl_change_yesterday": null,
          "pl_change_weekly": null,
          "pl_change_monthly": null,
          "pl_lifetime": null,
          "scalper_score": 0,
          "scalper_percent": null,
          "scalper": "0.00% (0/0)",
          "slippage_score": 0,
          "slippage_percent": null,
          "slippage": "0.00% (0/0)",
          "status": "Aman",
          "status_spv": null
      },
      {
          "name": "afridho zega",
          "server": "MT4IN4",
          "login": 1117140,
          "total_ticket": 0,
          "equity": 0,
          "currency": "USD",
          "ma_date": null,
          "opc_20": 0,
          "opp_50": 0,
          "daily_pl_20": 0,
          "mr": 0,
          "mr_percent": 0,
          "big_lot": 0,
          "last_equity": -2,
          "nnhl": null,
          "nnhl_score": 0,
          "nnhl_percent": 0,
          "av_profit_score": 0,
          "av_percent": null,
          "av_profit": "0.00% (0/)",
          "high_leverage_score": 0,
          "high_leverage_percent": null,
          "high_leverage": "0.00% (0/)",
          "pl_2_5_score": 0,
          "pl_2_5_percent": null,
          "pl_2_5": "0.00% (0/)",
          "pl_change": null,
          "pl_change_yesterday": null,
          "pl_change_weekly": null,
          "pl_change_monthly": null,
          "pl_lifetime": null,
          "scalper_score": 0,
          "scalper_percent": null,
          "scalper": "0.00% (0/0)",
          "slippage_score": 0,
          "slippage_percent": null,
          "slippage": "0.00% (0/0)",
          "status": "Action",
          "status_spv": null
      },
      {
          "name": "debug account",
          "server": "MT4IN4",
          "login": 1117140,
          "total_ticket": 0,
          "equity": 0,
          "currency": "USD",
          "ma_date": "2018-01-16 00:00:00",
          "opc_20": 0,
          "opp_50": 0,
          "daily_pl_20": 0,
          "mr": 0,
          "mr_percent": 0,
          "big_lot": 0,
          "last_equity": -4,
          "nnhl": null,
          "nnhl_score": 0,
          "nnhl_percent": 0,
          "av_profit_score": 0,
          "av_percent": null,
          "av_profit": "0.00% (0/)",
          "high_leverage_score": 0,
          "high_leverage_percent": null,
          "high_leverage": "0.00% (0/)",
          "pl_2_5_score": 0,
          "pl_2_5_percent": null,
          "pl_2_5": "0.00% (0/)",
          "pl_change": null,
          "pl_change_yesterday": null,
          "pl_change_weekly": null,
          "pl_change_monthly": null,
          "pl_lifetime": null,
          "scalper_score": 0,
          "scalper_percent": null,
          "scalper": "0.00% (0/0)",
          "slippage_score": 0,
          "slippage_percent": null,
          "slippage": "0.00% (0/0)",
          "status": "Baru",
          "status_spv": null
      },
      {
          "name": "google",
          "server": "MT4HK",
          "login": 88897889,
          "total_ticket": 0,
          "equity": 0,
          "currency": "USD",
          "ma_date": null,
          "opc_20": 0,
          "opp_50": 0,
          "daily_pl_20": 0,
          "mr": 0,
          "mr_percent": 0,
          "big_lot": 0,
          "last_equity": 0,
          "nnhl": null,
          "nnhl_score": 0,
          "nnhl_percent": 0,
          "av_profit_score": 0,
          "av_percent": null,
          "av_profit": "0.00% (0/)",
          "high_leverage_score": 0,
          "high_leverage_percent": null,
          "high_leverage": "0.00% (0/)",
          "pl_2_5_score": 0,
          "pl_2_5_percent": null,
          "pl_2_5": "0.00% (0/)",
          "pl_change": null,
          "pl_change_yesterday": null,
          "pl_change_weekly": null,
          "pl_change_monthly": null,
          "pl_lifetime": null,
          "scalper_score": 0,
          "scalper_percent": null,
          "scalper": "0.00% (0/0)",
          "slippage_score": 0,
          "slippage_percent": null,
          "slippage": "0.00% (0/0)",
          "status": "Action",
          "status_spv": null
      },
      {
          "name": "twitter",
          "server": "MT4CYPRUS",
          "login": 30053930,
          "total_ticket": 0,
          "equity": 99.88,
          "currency": "USD",
          "ma_date": null,
          "opc_20": 0,
          "opp_50": 0,
          "daily_pl_20": 0,
          "mr": 0,
          "mr_percent": 0,
          "big_lot": 0,
          "last_equity": 0,
          "nnhl": null,
          "nnhl_score": 0,
          "nnhl_percent": 0,
          "av_profit_score": 0,
          "av_percent": null,
          "av_profit": "0.00% (0/)",
          "high_leverage_score": 0,
          "high_leverage_percent": null,
          "high_leverage": "0.00% (0/)",
          "pl_2_5_score": 0,
          "pl_2_5_percent": null,
          "pl_2_5": "0.00% (0/)",
          "pl_change": null,
          "pl_change_yesterday": null,
          "pl_change_weekly": null,
          "pl_change_monthly": null,
          "pl_lifetime": null,
          "scalper_score": 0,
          "scalper_percent": null,
          "scalper": "0.00% (0/0)",
          "slippage_score": 0,
          "slippage_percent": null,
          "slippage": "0.00% (0/0)",
          "status": "Baru",
          "status_spv": null
      },
      {
          "name": "makan",
          "server": "MT4HK",
          "login": 88888417,
          "total_ticket": 0,
          "equity": 0,
          "currency": "USD",
          "ma_date": null,
          "opc_20": 0,
          "opp_50": 0,
          "daily_pl_20": 0,
          "mr": 0,
          "mr_percent": 0,
          "big_lot": 0,
          "last_equity": 0,
          "nnhl": null,
          "nnhl_score": 0,
          "nnhl_percent": 0,
          "av_profit_score": 0,
          "av_percent": null,
          "av_profit": "0.00% (0/)",
          "high_leverage_score": 0,
          "high_leverage_percent": null,
          "high_leverage": "0.00% (0/)",
          "pl_2_5_score": 0,
          "pl_2_5_percent": null,
          "pl_2_5": "0.00% (0/)",
          "pl_change": null,
          "pl_change_yesterday": null,
          "pl_change_weekly": null,
          "pl_change_monthly": null,
          "pl_lifetime": null,
          "scalper_score": 0,
          "scalper_percent": null,
          "scalper": "0.00% (0/0)",
          "slippage_score": 0,
          "slippage_percent": null,
          "slippage": "0.00% (0/0)",
          "status": "Action",
          "status_spv": null
      },
      {
          "name": "apple",
          "server": "MT4CYPRUS",
          "login": 30034261,
          "total_ticket": 0,
          "equity": 1.22,
          "currency": "USD",
          "ma_date": "2017-11-01 00:00:00",
          "opc_20": 0,
          "opp_50": 0,
          "daily_pl_20": 0,
          "mr": 0,
          "mr_percent": 0,
          "big_lot": 0,
          "last_equity": 0,
          "nnhl": null,
          "nnhl_score": 0,
          "nnhl_percent": 0,
          "av_profit_score": 0,
          "av_percent": null,
          "av_profit": "0.00% (0/)",
          "high_leverage_score": 0,
          "high_leverage_percent": null,
          "high_leverage": "0.00% (0/)",
          "pl_2_5_score": 0,
          "pl_2_5_percent": null,
          "pl_2_5": "0.00% (0/)",
          "pl_change": null,
          "pl_change_yesterday": null,
          "pl_change_weekly": null,
          "pl_change_monthly": null,
          "pl_lifetime": null,
          "scalper_score": 0,
          "scalper_percent": null,
          "scalper": "0.00% (0/0)",
          "slippage_score": 0,
          "slippage_percent": null,
          "slippage": "0.00% (0/0)",
          "status": "Baru",
          "status_spv": null
      },
      {
          "name": "iphone",
          "server": "MT4HK",
          "login": 88990149,
          "total_ticket": 0,
          "equity": 0,
          "currency": "USD",
          "ma_date": null,
          "opc_20": 0,
          "opp_50": 0,
          "daily_pl_20": 0,
          "mr": 0,
          "mr_percent": 0,
          "big_lot": 0,
          "last_equity": 0,
          "nnhl": null,
          "nnhl_score": 0,
          "nnhl_percent": 0,
          "av_profit_score": 0,
          "av_percent": null,
          "av_profit": "0.00% (0/)",
          "high_leverage_score": 0,
          "high_leverage_percent": null,
          "high_leverage": "0.00% (0/)",
          "pl_2_5_score": 0,
          "pl_2_5_percent": null,
          "pl_2_5": "0.00% (0/)",
          "pl_change": null,
          "pl_change_yesterday": null,
          "pl_change_weekly": null,
          "pl_change_monthly": null,
          "pl_lifetime": null,
          "scalper_score": 0,
          "scalper_percent": null,
          "scalper": "0.00% (0/0)",
          "slippage_score": 0,
          "slippage_percent": null,
          "slippage": "0.00% (0/0)",
          "status": "Pantau",
          "status_spv": null
      },
      {
          "name": "angular",
          "server": "MT4HK",
          "login": 88889991,
          "total_ticket": 0,
          "equity": 0,
          "currency": "USD",
          "ma_date": null,
          "opc_20": 0,
          "opp_50": 0,
          "daily_pl_20": 0,
          "mr": 0,
          "mr_percent": 0,
          "big_lot": 0,
          "last_equity": 0,
          "nnhl": null,
          "nnhl_score": 0,
          "nnhl_percent": 0,
          "av_profit_score": 0,
          "av_percent": null,
          "av_profit": "0.00% (0/)",
          "high_leverage_score": 0,
          "high_leverage_percent": null,
          "high_leverage": "0.00% (0/)",
          "pl_2_5_score": 0,
          "pl_2_5_percent": null,
          "pl_2_5": "0.00% (0/)",
          "pl_change": null,
          "pl_change_yesterday": null,
          "pl_change_weekly": null,
          "pl_change_monthly": null,
          "pl_lifetime": null,
          "scalper_score": 0,
          "scalper_percent": null,
          "scalper": "0.00% (0/0)",
          "slippage_score": 0,
          "slippage_percent": null,
          "slippage": "0.00% (0/0)",
          "status": "Aman",
          "status_spv": null
      },
      {
          "name": "nokia",
          "server": "MT4HK",
          "login": 88889992,
          "total_ticket": 0,
          "equity": 0,
          "currency": "USD",
          "ma_date": null,
          "opc_20": 0,
          "opp_50": 0,
          "daily_pl_20": 0,
          "mr": 0,
          "mr_percent": 0,
          "big_lot": 0,
          "last_equity": 0,
          "nnhl": null,
          "nnhl_score": 0,
          "nnhl_percent": 0,
          "av_profit_score": 0,
          "av_percent": null,
          "av_profit": "0.00% (0/)",
          "high_leverage_score": 0,
          "high_leverage_percent": null,
          "high_leverage": "0.00% (0/)",
          "pl_2_5_score": 0,
          "pl_2_5_percent": null,
          "pl_2_5": "0.00% (0/)",
          "pl_change": null,
          "pl_change_yesterday": null,
          "pl_change_weekly": null,
          "pl_change_monthly": null,
          "pl_lifetime": null,
          "scalper_score": 0,
          "scalper_percent": null,
          "scalper": "0.00% (0/0)",
          "slippage_score": 0,
          "slippage_percent": null,
          "slippage": "0.00% (0/0)",
          "status": "Bahaya",
          "status_spv": null
      },
      {
          "name": "samsung",
          "server": "MT4HK",
          "login": 88889993,
          "total_ticket": 0,
          "equity": 0,
          "currency": "USD",
          "ma_date": null,
          "opc_20": 0,
          "opp_50": 0,
          "daily_pl_20": 0,
          "mr": 0,
          "mr_percent": 0,
          "big_lot": 0,
          "last_equity": 0,
          "nnhl": null,
          "nnhl_score": 0,
          "nnhl_percent": 0,
          "av_profit_score": 0,
          "av_percent": null,
          "av_profit": "0.00% (0/)",
          "high_leverage_score": 0,
          "high_leverage_percent": null,
          "high_leverage": "0.00% (0/)",
          "pl_2_5_score": 0,
          "pl_2_5_percent": null,
          "pl_2_5": "0.00% (0/)",
          "pl_change": null,
          "pl_change_yesterday": null,
          "pl_change_weekly": null,
          "pl_change_monthly": null,
          "pl_lifetime": null,
          "scalper_score": 0,
          "scalper_percent": null,
          "scalper": "0.00% (0/0)",
          "slippage_score": 0,
          "slippage_percent": null,
          "slippage": "0.00% (0/0)",
          "status": "Aman",
          "status_spv": null
      },
      {
          "name": "yamaha",
          "server": "MT4HK",
          "login": 88889994,
          "total_ticket": 0,
          "equity": 0,
          "currency": "USD",
          "ma_date": null,
          "opc_20": 0,
          "opp_50": 0,
          "daily_pl_20": 0,
          "mr": 0,
          "mr_percent": 0,
          "big_lot": 0,
          "last_equity": 0,
          "nnhl": null,
          "nnhl_score": 0,
          "nnhl_percent": 0,
          "av_profit_score": 0,
          "av_percent": null,
          "av_profit": "0.00% (0/)",
          "high_leverage_score": 0,
          "high_leverage_percent": null,
          "high_leverage": "0.00% (0/)",
          "pl_2_5_score": 0,
          "pl_2_5_percent": null,
          "pl_2_5": "0.00% (0/)",
          "pl_change": null,
          "pl_change_yesterday": null,
          "pl_change_weekly": null,
          "pl_change_monthly": null,
          "pl_lifetime": null,
          "scalper_score": 0,
          "scalper_percent": null,
          "scalper": "0.00% (0/0)",
          "slippage_score": 0,
          "slippage_percent": null,
          "slippage": "0.00% (0/0)",
          "status": "Aman",
          "status_spv": null
      },
      {
          "name": "honda",
          "server": "MT4HK",
          "login": 88889995,
          "total_ticket": 0,
          "equity": 0,
          "currency": "USD",
          "ma_date": null,
          "opc_20": 0,
          "opp_50": 0,
          "daily_pl_20": 0,
          "mr": 0,
          "mr_percent": 0,
          "big_lot": 0,
          "last_equity": 0,
          "nnhl": null,
          "nnhl_score": 0,
          "nnhl_percent": 0,
          "av_profit_score": 0,
          "av_percent": null,
          "av_profit": "0.00% (0/)",
          "high_leverage_score": 0,
          "high_leverage_percent": null,
          "high_leverage": "0.00% (0/)",
          "pl_2_5_score": 0,
          "pl_2_5_percent": null,
          "pl_2_5": "0.00% (0/)",
          "pl_change": null,
          "pl_change_yesterday": null,
          "pl_change_weekly": null,
          "pl_change_monthly": null,
          "pl_lifetime": null,
          "scalper_score": 0,
          "scalper_percent": null,
          "scalper": "0.00% (0/0)",
          "slippage_score": 0,
          "slippage_percent": null,
          "slippage": "0.00% (0/0)",
          "status": "Baru",
          "status_spv": null
      },
      {
          "name": "erigo",
          "server": "MT4HK",
          "login": 88889996,
          "total_ticket": 0,
          "equity": 0,
          "currency": "USD",
          "ma_date": null,
          "opc_20": 0,
          "opp_50": 0,
          "daily_pl_20": 0,
          "mr": 0,
          "mr_percent": 0,
          "big_lot": 0,
          "last_equity": 0,
          "nnhl": null,
          "nnhl_score": 0,
          "nnhl_percent": 0,
          "av_profit_score": 0,
          "av_percent": null,
          "av_profit": "0.00% (0/)",
          "high_leverage_score": 0,
          "high_leverage_percent": null,
          "high_leverage": "0.00% (0/)",
          "pl_2_5_score": 0,
          "pl_2_5_percent": null,
          "pl_2_5": "0.00% (0/)",
          "pl_change": null,
          "pl_change_yesterday": null,
          "pl_change_weekly": null,
          "pl_change_monthly": null,
          "pl_lifetime": null,
          "scalper_score": 0,
          "scalper_percent": null,
          "scalper": "0.00% (0/0)",
          "slippage_score": 0,
          "slippage_percent": null,
          "slippage": "0.00% (0/0)",
          "status": "Baru",
          "status_spv": null
      },
      {
          "name": "visual code",
          "server": "MT4HK",
          "login": 88889997,
          "total_ticket": 0,
          "equity": 0,
          "currency": "USD",
          "ma_date": null,
          "opc_20": 0,
          "opp_50": 0,
          "daily_pl_20": 0,
          "mr": 0,
          "mr_percent": 0,
          "big_lot": 0,
          "last_equity": 0,
          "nnhl": null,
          "nnhl_score": 0,
          "nnhl_percent": 0,
          "av_profit_score": 0,
          "av_percent": null,
          "av_profit": "0.00% (0/)",
          "high_leverage_score": 0,
          "high_leverage_percent": null,
          "high_leverage": "0.00% (0/)",
          "pl_2_5_score": 0,
          "pl_2_5_percent": null,
          "pl_2_5": "0.00% (0/)",
          "pl_change": null,
          "pl_change_yesterday": null,
          "pl_change_weekly": null,
          "pl_change_monthly": null,
          "pl_lifetime": null,
          "scalper_score": 0,
          "scalper_percent": null,
          "scalper": "0.00% (0/0)",
          "slippage_score": 0,
          "slippage_percent": null,
          "slippage": "0.00% (0/0)",
          "status": "Action",
          "status_spv": null
      }
  ],
  "first_page_url": "https://rpt-rmv3-dev.surya-am.com/api/v1/triggered-report?search=USD&sort=name&page=1",
  "from": 1,
  "last_page": 5266,
  "last_page_url": "https://rpt-rmv3-dev.surya-am.com/api/v1/triggered-report?search=USD&sort=name&page=5266",
  "links": [
      {
          "url": null,
          "label": "&laquo; Previous",
          "active": false
      },
      {
          "url": "https://rpt-rmv3-dev.surya-am.com/api/v1/triggered-report?search=USD&sort=name&page=1",
          "label": "1",
          "active": true
      },
      {
          "url": "https://rpt-rmv3-dev.surya-am.com/api/v1/triggered-report?search=USD&sort=name&page=2",
          "label": "2",
          "active": false
      },
      {
          "url": "https://rpt-rmv3-dev.surya-am.com/api/v1/triggered-report?search=USD&sort=name&page=3",
          "label": "3",
          "active": false
      },
      {
          "url": "https://rpt-rmv3-dev.surya-am.com/api/v1/triggered-report?search=USD&sort=name&page=4",
          "label": "4",
          "active": false
      },
      {
          "url": "https://rpt-rmv3-dev.surya-am.com/api/v1/triggered-report?search=USD&sort=name&page=5",
          "label": "5",
          "active": false
      },
      {
          "url": "https://rpt-rmv3-dev.surya-am.com/api/v1/triggered-report?search=USD&sort=name&page=6",
          "label": "6",
          "active": false
      },
      {
          "url": "https://rpt-rmv3-dev.surya-am.com/api/v1/triggered-report?search=USD&sort=name&page=7",
          "label": "7",
          "active": false
      },
      {
          "url": "https://rpt-rmv3-dev.surya-am.com/api/v1/triggered-report?search=USD&sort=name&page=8",
          "label": "8",
          "active": false
      },
      {
          "url": "https://rpt-rmv3-dev.surya-am.com/api/v1/triggered-report?search=USD&sort=name&page=9",
          "label": "9",
          "active": false
      },
      {
          "url": "https://rpt-rmv3-dev.surya-am.com/api/v1/triggered-report?search=USD&sort=name&page=10",
          "label": "10",
          "active": false
      },
      {
          "url": null,
          "label": "...",
          "active": false
      },
      {
          "url": "https://rpt-rmv3-dev.surya-am.com/api/v1/triggered-report?search=USD&sort=name&page=5265",
          "label": "5265",
          "active": false
      },
      {
          "url": "https://rpt-rmv3-dev.surya-am.com/api/v1/triggered-report?search=USD&sort=name&page=5266",
          "label": "5266",
          "active": false
      },
      {
          "url": "https://rpt-rmv3-dev.surya-am.com/api/v1/triggered-report?search=USD&sort=name&page=2",
          "label": "Next &raquo;",
          "active": false
      }
  ],
  "next_page_url": "https://rpt-rmv3-dev.surya-am.com/api/v1/triggered-report?search=USD&sort=name&page=2",
  "path": "https://rpt-rmv3-dev.surya-am.com/api/v1/triggered-report",
  "per_page": 15,
  "prev_page_url": null,
  "to": 15,
  "total": 78979
}

module.exports = data;