var data = {
    "status": true,
    "message": "Success",
    "data": [
        {
            "id": 1,
            "name": "Home",
            "icon": "home",
            "url": "\/apps\/dashboards\/analytics",
            "is_parent": 0,
            "parent_id": 0,
            "level": 0,
            "type": "item",
            "group_name": "home",
            "child": []
        },
        {
            "id": 2,
            "name": "CEO Dashboard",
            "icon": "home",
            "url": "\/ceo-dashboard",
            "is_parent": 1,
            "parent_id": 0,
            "level": 0,
            "type": "collapsable",
            "group_name": "ceo",
            "child": [
                {
                    "id": 3,
                    "name": "Dashboard",
                    "icon": "dashboard",
                    "url": "\/ceo\/dashboard",
                    "is_parent": 0,
                    "parent_id": 2,
                    "level": 1,
                    "type": "item",
                    "group_name": "ceo",
                    "child": []
                },
                {
                    "id": 4,
                    "name": "Conversion",
                    "icon": "money",
                    "url": "\/ceo\/conversion",
                    "is_parent": 0,
                    "parent_id": 2,
                    "level": 2,
                    "type": "item",
                    "group_name": "ceo",
                    "child": []
                }
            ]
        },
        {
            "id": 5,
            "name": "Development",
            "icon": "group_work",
            "url": "\/development",
            "is_parent": 1,
            "parent_id": 0,
            "level": 0,
            "type": "collapsable",
            "group_name": "development",
            "child": [
                {
                    "id": 6,
                    "name": "Report Slip Page",
                    "icon": "compare_arrows",
                    "url": "\/development\/report-slip-page",
                    "is_parent": 0,
                    "parent_id": 5,
                    "level": 1,
                    "type": "item",
                    "group_name": "development",
                    "child": []
                },
                {
                    "id": 7,
                    "name": "Daily History",
                    "icon": "show_chart",
                    "url": "\/development\/daily-history",
                    "is_parent": 0,
                    "parent_id": 5,
                    "level": 2,
                    "type": "item",
                    "group_name": "development",
                    "child": []
                },
                {
                    "id": 8,
                    "name": "Tick Account",
                    "icon": "timeline",
                    "url": "\/development\/tick-account",
                    "is_parent": 0,
                    "parent_id": 5,
                    "level": 3,
                    "type": "item",
                    "group_name": "development",
                    "child": []
                },
                {
                    "id": 9,
                    "name": "MA Info",
                    "icon": "multiline_chart",
                    "url": "\/development\/ma-info",
                    "is_parent": 0,
                    "parent_id": 5,
                    "level": 4,
                    "type": "item",
                    "group_name": "development",
                    "child": []
                },
                {
                    "id": 10,
                    "name": "Reopen Trades",
                    "icon": "restore",
                    "url": "\/development\/reopen-trades",
                    "is_parent": 0,
                    "parent_id": 5,
                    "level": 5,
                    "type": "item",
                    "group_name": "development",
                    "child": []
                },
                {
                    "id": 11,
                    "name": "Deleted Record",
                    "icon": "clear",
                    "url": "\/development\/deleted-record",
                    "is_parent": 0,
                    "parent_id": 5,
                    "level": 6,
                    "type": "item",
                    "group_name": "development",
                    "child": []
                },
                {
                    "id": 12,
                    "name": "Analyze Spread",
                    "icon": "linear_scale",
                    "url": "\/development\/analyze-spread",
                    "is_parent": 0,
                    "parent_id": 5,
                    "level": 7,
                    "type": "item",
                    "group_name": "development",
                    "child": []
                },
                {
                    "id": 13,
                    "name": "Filter Group",
                    "icon": "supervised_user_circle",
                    "url": "\/development\/filter-group",
                    "is_parent": 0,
                    "parent_id": 5,
                    "level": 8,
                    "type": "item",
                    "group_name": "development",
                    "child": []
                },
                {
                    "id": 15,
                    "name": "Sentiment",
                    "icon": "timeline",
                    "url": "\/development\/sentiment",
                    "is_parent": 0,
                    "parent_id": 5,
                    "level": 10,
                    "type": "item",
                    "group_name": "development",
                    "child": []
                }
            ]
        },
        {
            "id": 16,
            "name": "Report",
            "icon": "description",
            "url": "\/report",
            "is_parent": 1,
            "parent_id": 0,
            "level": 0,
            "type": "collapsable",
            "group_name": "report",
            "child": [
                {
                    "id": 17,
                    "name": "Big Lot",
                    "icon": "description",
                    "url": "\/report\/big-lot",
                    "is_parent": 0,
                    "parent_id": 16,
                    "level": 1,
                    "type": "item",
                    "group_name": "report",
                    "child": []
                },
                {
                    "id": 18,
                    "name": "MTM Journal",
                    "icon": "description",
                    "url": "\/report\/mtm-journal",
                    "is_parent": 0,
                    "parent_id": 16,
                    "level": 2,
                    "type": "item",
                    "group_name": "report",
                    "child": []
                },
                {
                    "id": 19,
                    "name": "Modified Pending Tickets",
                    "icon": "description",
                    "url": "\/report\/modified-pending-tickets",
                    "is_parent": 0,
                    "parent_id": 16,
                    "level": 3,
                    "type": "item",
                    "group_name": "report",
                    "child": []
                },
                {
                    "id": 20,
                    "name": "Free Margin",
                    "icon": "description",
                    "url": "\/report\/free-margin",
                    "is_parent": 0,
                    "parent_id": 16,
                    "level": 4,
                    "type": "item",
                    "group_name": "report",
                    "child": []
                },
                {
                    "id": 21,
                    "name": "Net Volume",
                    "icon": "description",
                    "url": "\/report\/net-volume",
                    "is_parent": 0,
                    "parent_id": 16,
                    "level": 5,
                    "type": "item",
                    "group_name": "report",
                    "child": []
                },
                {
                    "id": 22,
                    "name": "Report Profile A",
                    "icon": "description",
                    "url": "\/report\/mirror-report",
                    "is_parent": 0,
                    "parent_id": 16,
                    "level": 6,
                    "type": "item",
                    "group_name": "report",
                    "child": []
                },
                {
                    "id": 23,
                    "name": "Stopout",
                    "icon": "description",
                    "url": "\/report\/stopout",
                    "is_parent": 0,
                    "parent_id": 16,
                    "level": 7,
                    "type": "item",
                    "group_name": "report",
                    "child": []
                },
                {
                    "id": 24,
                    "name": "Open Position",
                    "icon": "description",
                    "url": "\/report\/open-position",
                    "is_parent": 0,
                    "parent_id": 16,
                    "level": 8,
                    "type": "item",
                    "group_name": "report",
                    "child": []
                },
                {
                    "id": 25,
                    "name": "TP Range",
                    "icon": "show_chart",
                    "url": "\/report\/tp-range",
                    "is_parent": 0,
                    "parent_id": 16,
                    "level": 9,
                    "type": "item",
                    "group_name": "report",
                    "child": []
                }
            ]
        },
        {
            "id": 26,
            "name": "Profile A",
            "icon": "stars",
            "url": "\/profilea",
            "is_parent": 1,
            "parent_id": 0,
            "level": 0,
            "type": "collapsable",
            "group_name": "profilea",
            "child": [
                {
                    "id": 27,
                    "name": "Accounts",
                    "icon": "bookmarks",
                    "url": "\/profilea\/accounts",
                    "is_parent": 0,
                    "parent_id": 26,
                    "level": 1,
                    "type": "item",
                    "group_name": "profilea",
                    "child": []
                },
                {
                    "id": 28,
                    "name": "Accounts (Disabled)",
                    "icon": "bookmarks",
                    "url": "\/profilea\/accounts-disabled",
                    "is_parent": 0,
                    "parent_id": 26,
                    "level": 2,
                    "type": "item",
                    "group_name": "profilea",
                    "child": []
                },
                {
                    "id": 29,
                    "name": "Accounts VT",
                    "icon": "bookmarks",
                    "url": "\/profilea\/accounts-vt",
                    "is_parent": 0,
                    "parent_id": 26,
                    "level": 3,
                    "type": "item",
                    "group_name": "profilea",
                    "child": []
                },
                {
                    "id": 30,
                    "name": "Accounts VT (Disabled)",
                    "icon": "bookmarks",
                    "url": "\/profilea\/accounts-vt-disabled",
                    "is_parent": 0,
                    "parent_id": 26,
                    "level": 4,
                    "type": "item",
                    "group_name": "profilea",
                    "child": []
                },
                {
                    "id": 31,
                    "name": "Group Trade",
                    "icon": "file_copy",
                    "url": "\/profilea\/group-trade",
                    "is_parent": 0,
                    "parent_id": 26,
                    "level": 5,
                    "type": "item",
                    "group_name": "profilea",
                    "child": []
                },
                {
                    "id": 32,
                    "name": "Equity Highest Lowest",
                    "icon": "show_chart",
                    "url": "\/profilea\/equity-highest-lowest",
                    "is_parent": 0,
                    "parent_id": 26,
                    "level": 6,
                    "type": "item",
                    "group_name": "profilea",
                    "child": []
                },
                {
                    "id": 33,
                    "name": "Equity Record",
                    "icon": "timeline",
                    "url": "\/profilea\/equity-record",
                    "is_parent": 0,
                    "parent_id": 26,
                    "level": 7,
                    "type": "item",
                    "group_name": "profilea",
                    "child": []
                },
                {
                    "id": 34,
                    "name": "Equity Trigger History",
                    "icon": "description",
                    "url": "\/profilea\/equity-trigger-history",
                    "is_parent": 0,
                    "parent_id": 26,
                    "level": 8,
                    "type": "item",
                    "group_name": "profilea",
                    "child": []
                },
                {
                    "id": 35,
                    "name": "Data Combine",
                    "icon": "list",
                    "url": "\/profilea\/data-combine",
                    "is_parent": 0,
                    "parent_id": 26,
                    "level": 9,
                    "type": "item",
                    "group_name": "profilea",
                    "child": []
                },
                {
                    "id": 36,
                    "name": "File Source",
                    "icon": "file_copy",
                    "url": "\/profilea\/filesource",
                    "is_parent": 0,
                    "parent_id": 26,
                    "level": 10,
                    "type": "item",
                    "group_name": "profilea",
                    "child": []
                },
                {
                    "id": 37,
                    "name": "FTP",
                    "icon": "move_to_inbox",
                    "url": "\/profilea\/ftp",
                    "is_parent": 0,
                    "parent_id": 26,
                    "level": 11,
                    "type": "item",
                    "group_name": "profilea",
                    "child": []
                },
                {
                    "id": 38,
                    "name": "Trade Monitoring",
                    "icon": "computer",
                    "url": "\/profilea\/trade-monitoring",
                    "is_parent": 0,
                    "parent_id": 26,
                    "level": 12,
                    "type": "item",
                    "group_name": "profilea",
                    "child": []
                },
                {
                    "id": 39,
                    "name": "Manual Trigger",
                    "icon": "schedule",
                    "url": "\/profilea\/manual-trigger",
                    "is_parent": 0,
                    "parent_id": 26,
                    "level": 13,
                    "type": "item",
                    "group_name": "profilea",
                    "child": []
                }
            ]
        },
        {
            "id": 43,
            "name": "Trailing",
            "icon": "android",
            "url": "\/trailing",
            "is_parent": 1,
            "parent_id": 0,
            "level": 0,
            "type": "collapsable",
            "group_name": "trailing",
            "child": [
                {
                    "id": 44,
                    "name": "Auto Config",
                    "icon": "build",
                    "url": "\/trailing\/auto-config",
                    "is_parent": 0,
                    "parent_id": 43,
                    "level": 1,
                    "type": "item",
                    "group_name": "trailing",
                    "child": []
                },
                {
                    "id": 45,
                    "name": "Account Position",
                    "icon": "assignment",
                    "url": "\/trailing\/account-position",
                    "is_parent": 0,
                    "parent_id": 43,
                    "level": 2,
                    "type": "item",
                    "group_name": "trailing",
                    "child": []
                },
                {
                    "id": 46,
                    "name": "Manual Sync",
                    "icon": "restore",
                    "url": "\/trailing\/manual-sync",
                    "is_parent": 0,
                    "parent_id": 43,
                    "level": 3,
                    "type": "item",
                    "group_name": "trailing",
                    "child": []
                }
            ]
        },
        {
            "id": 47,
            "name": "Scoring",
            "icon": "apps",
            "url": "\/scoring",
            "is_parent": 1,
            "parent_id": 0,
            "level": 0,
            "type": "collapsable",
            "group_name": "scoring",
            "child": [
                {
                    "id": 48,
                    "name": "Latest Triggered",
                    "icon": "description",
                    "url": "\/scoring\/latest-triggered",
                    "is_parent": 0,
                    "parent_id": 47,
                    "level": 1,
                    "type": "item",
                    "group_name": "scoring",
                    "child": []
                },
                {
                    "id": 49,
                    "name": "Triggered Report",
                    "icon": "description",
                    "url": "\/scoring\/triggered-report",
                    "is_parent": 0,
                    "parent_id": 47,
                    "level": 2,
                    "type": "item",
                    "group_name": "scoring",
                    "child": []
                },
                {
                    "id": 50,
                    "name": "Lifetime Lot",
                    "icon": "description",
                    "url": "\/scoring\/livetime-lot",
                    "is_parent": 0,
                    "parent_id": 47,
                    "level": 3,
                    "type": "item",
                    "group_name": "scoring",
                    "child": []
                }
            ]
        },
        {
            "id": 51,
            "name": "User Management",
            "icon": "accessibility",
            "url": "\/user-management",
            "is_parent": 1,
            "parent_id": 0,
            "level": 0,
            "type": "collapsable",
            "group_name": "user",
            "child": [
                {
                    "id": 52,
                    "name": "User",
                    "icon": "person_pin",
                    "url": "\/user-management\/users",
                    "is_parent": 0,
                    "parent_id": 51,
                    "level": 1,
                    "type": "item",
                    "group_name": "user",
                    "child": []
                },
                {
                    "id": 53,
                    "name": "User Groups",
                    "icon": "supervised_user_circle",
                    "url": "\/user-management\/user-groups",
                    "is_parent": 0,
                    "parent_id": 51,
                    "level": 2,
                    "type": "item",
                    "group_name": "user",
                    "child": []
                }
            ]
        },
        {
            "id": 54,
            "name": "Tools",
            "icon": "settings",
            "url": "\/tools",
            "is_parent": 1,
            "parent_id": 0,
            "level": 0,
            "type": "collapsable",
            "group_name": "tools",
            "child": [
                {
                    "id": 55,
                    "name": "Settings",
                    "icon": "settings_applications",
                    "url": "\/tools\/settings",
                    "is_parent": 0,
                    "parent_id": 54,
                    "level": 1,
                    "type": "item",
                    "group_name": "tools",
                    "child": []
                },
                {
                    "id": 56,
                    "name": "Upload CSV",
                    "icon": "cloud_upload",
                    "url": "\/csv-uploader",
                    "is_parent": 0,
                    "parent_id": 54,
                    "level": 2,
                    "type": "item",
                    "group_name": "tools",
                    "child": []
                },
                {
                    "id": 57,
                    "name": "Deleted Accounts",
                    "icon": "person_pin",
                    "url": "\/tools\/deleted-accounts",
                    "is_parent": 0,
                    "parent_id": 54,
                    "level": 3,
                    "type": "item",
                    "group_name": "tools",
                    "child": []
                },
                {
                    "id": 58,
                    "name": "Daily Report",
                    "icon": "description",
                    "url": "\/tools\/daily-report",
                    "is_parent": 0,
                    "parent_id": 54,
                    "level": 4,
                    "type": "item",
                    "group_name": "tools",
                    "child": []
                },
                {
                    "id": 59,
                    "name": "Group Symbol",
                    "icon": "attach_money",
                    "url": "\/tools\/group-symbol",
                    "is_parent": 0,
                    "parent_id": 54,
                    "level": 5,
                    "type": "item",
                    "group_name": "tools",
                    "child": []
                },
                {
                    "id": 60,
                    "name": "Summary Revision",
                    "icon": "rotate_left",
                    "url": "\/tools\/summary-revision",
                    "is_parent": 0,
                    "parent_id": 54,
                    "level": 6,
                    "type": "item",
                    "group_name": "tools",
                    "child": []
                },
                {
                    "id": 61,
                    "name": "Score",
                    "icon": "exposure_plus_1",
                    "url": "\/tools\/score",
                    "is_parent": 0,
                    "parent_id": 54,
                    "level": 7,
                    "type": "item",
                    "group_name": "tools",
                    "child": []
                },
                {
                    "id": 62,
                    "name": "Scalper Symbol",
                    "icon": "compare_arrows",
                    "url": "\/tools\/scalper-symbol",
                    "is_parent": 0,
                    "parent_id": 54,
                    "level": 8,
                    "type": "item",
                    "group_name": "tools",
                    "child": []
                },
                {
                    "id": 63,
                    "name": "Setting Warehouse",
                    "icon": "cloud_upload",
                    "url": "\/tools\/setting-warehouse",
                    "is_parent": 0,
                    "parent_id": 54,
                    "level": 9,
                    "type": "item",
                    "group_name": "tools",
                    "child": []
                }
            ]
        }
    ]
}

module.exports = data