name: Deployment Status Notification
on: [deployment_status]

jobs:
    add-pushover-notification:
        name: Add a Pushover Notification
        environment: production
        runs-on: ubuntu-latest
        steps:
            - name: Add commit comment
              run: |
                  DEPLOYMENT_URL="${{ github.event.deployment_status.target_url }}"

                  curl -X POST "https://afridho-api.vercel.app/api/build-notification" \
                  -H "Content-Type: application/json" \
                  -d '{
                      "title": "Vercel",
                      "message": "'"${{ github.event.repository.name }} ▸ build ${{ github.event.deployment_status.state }}!"'",
                      "device": "ridhosmac",
                      "url_title": "View deployment",
                      "url": "'"${DEPLOYMENT_URL}"'",
                      "status": "'"${{ github.event.deployment_status.state }}"'"
                  }'
